# CIFAR10 with CNN
code from https://github.com/fchollet/keras/blob/master/examples/mnist_cnn.py


This notebook trains a simple convolutional neural network on the CIFAR10 small images dataset. 
Note: Although its seems like the epochs sometimes do not train until the end, this is only a visual issue. 



### Setup

In [10]:
# import libraries
from __future__ import print_function
from __future__ import print_function
import keras
from keras.datasets import cifar10
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D

#for confusion matrix
import numpy as np
import sklearn
from sklearn.metrics import confusion_matrix


In [11]:
# define constants
batch_size = 128
num_classes = 10
epochs = 20


# The data, shuffled and split between train and test sets:
(x_train, y_train), (x_test, y_test) = cifar10.load_data()
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# Convert class vectors to binary class matrices.
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

# Cast features into correct data type then scale features
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

x_train shape: (50000, 32, 32, 3)
50000 train samples
10000 test samples


### Base case

In [12]:
model = Sequential()

model.add(Conv2D(32, (3, 3), padding='same',
                 input_shape=x_train.shape[1:]))
model.add(Activation('relu'))
model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(64, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes))
model.add(Activation('softmax'))


In [13]:
# initiate RMSprop optimizer
opt = keras.optimizers.rmsprop(lr=0.0001, decay=1e-6)

# Let's train the model using RMSprop
model.compile(loss='categorical_crossentropy',
              optimizer=opt,
                metrics=['accuracy'])


model.fit(x_train, y_train,
            batch_size=batch_size,
            epochs=epochs,
            validation_data=(x_test, y_test),
            shuffle=True)

# Save the original model
model.save('cifra10_base.h5')



Train on 50000 samples, validate on 10000 samples
Epoch 1/20
50000/50000 [==============================] - 14s 273us/step - loss: 1.9615 - acc: 0.2762 - val_loss: 1.7035 - val_acc: 0.3952
Epoch 2/20
50000/50000 [==============================] - 13s 257us/step - loss: 1.6647 - acc: 0.3953 - val_loss: 1.5512 - val_acc: 0.4449
Epoch 3/20
 9344/50000 [====>.........................] - ETA: 9s - loss: 1.5881 - acc: 0.4238 

50000/50000 [==============================] - 13s 258us/step - loss: 1.5464 - acc: 0.4364 - val_loss: 1.4493 - val_acc: 0.4771
Epoch 4/20
50000/50000 [==============================] - 13s 259us/step - loss: 1.4681 - acc: 0.4676 - val_loss: 1.3638 - val_acc: 0.5108
Epoch 5/20
29824/50000 [================>.............] - ETA: 4s - loss: 1.4175 - acc: 0.4887

50000/50000 [==============================] - 13s 257us/step - loss: 1.4078 - acc: 0.4927 - val_loss: 1.3076 - val_acc: 0.5383
Epoch 6/20
50000/50000 [==============================] - 13s 260us/step - loss: 1.3538 - acc: 0.5161 - val_loss: 1.2917 - val_acc: 0.5386
Epoch 7/20
34176/50000 [===================>..........] - ETA: 3s - loss: 1.3202 - acc: 0.5307

50000/50000 [==============================] - 13s 259us/step - loss: 1.3119 - acc: 0.5344 - val_loss: 1.2189 - val_acc: 0.5699
Epoch 8/20
50000/50000 [==============================] - 13s 259us/step - loss: 1.2655 - acc: 0.5527 - val_loss: 1.1920 - val_acc: 0.5733
Epoch 9/20
34688/50000 [===================>..........] - ETA: 3s - loss: 1.2325 - acc: 0.5622

50000/50000 [==============================] - 13s 259us/step - loss: 1.2276 - acc: 0.5636 - val_loss: 1.1449 - val_acc: 0.5966
Epoch 10/20
50000/50000 [==============================] - 13s 258us/step - loss: 1.1890 - acc: 0.5813 - val_loss: 1.1207 - val_acc: 0.6036
Epoch 11/20
35712/50000 [====================>.........] - ETA: 3s - loss: 1.1615 - acc: 0.5863

50000/50000 [==============================] - 13s 259us/step - loss: 1.1569 - acc: 0.5901 - val_loss: 1.0678 - val_acc: 0.6214
Epoch 12/20
50000/50000 [==============================] - 13s 260us/step - loss: 1.1234 - acc: 0.6034 - val_loss: 1.0922 - val_acc: 0.6203
Epoch 13/20
34944/50000 [===================>..........] - ETA: 3s - loss: 1.0939 - acc: 0.6169

50000/50000 [==============================] - 13s 258us/step - loss: 1.0924 - acc: 0.6169 - val_loss: 1.0170 - val_acc: 0.6445
Epoch 14/20
50000/50000 [==============================] - 13s 259us/step - loss: 1.0641 - acc: 0.6255 - val_loss: 0.9874 - val_acc: 0.6555
Epoch 15/20
35200/50000 [====================>.........] - ETA: 3s - loss: 1.0420 - acc: 0.6360

50000/50000 [==============================] - 13s 260us/step - loss: 1.0382 - acc: 0.6363 - val_loss: 0.9699 - val_acc: 0.6605
Epoch 16/20
50000/50000 [==============================] - 13s 257us/step - loss: 1.0100 - acc: 0.6465 - val_loss: 0.9734 - val_acc: 0.6600
Epoch 17/20
35200/50000 [====================>.........] - ETA: 3s - loss: 0.9903 - acc: 0.6513

50000/50000 [==============================] - 13s 259us/step - loss: 0.9907 - acc: 0.6509 - val_loss: 0.9176 - val_acc: 0.6778
Epoch 18/20
50000/50000 [==============================] - 13s 258us/step - loss: 0.9709 - acc: 0.6605 - val_loss: 0.8981 - val_acc: 0.6840
Epoch 19/20
35712/50000 [====================>.........] - ETA: 3s - loss: 0.9510 - acc: 0.6661

50000/50000 [==============================] - 13s 258us/step - loss: 0.9498 - acc: 0.6657 - val_loss: 0.9161 - val_acc: 0.6816
Epoch 20/20
50000/50000 [==============================] - 13s 260us/step - loss: 0.9302 - acc: 0.6746 - val_loss: 0.8805 - val_acc: 0.6913


In [14]:
# Print base model loss and accuracy
print('\n  - Base case:')
model = keras.models.load_model("cifra10_base.h5")
scores = model.evaluate(x_test, y_test, verbose=0)
print('\tTest loss:\t', scores[0])
print('\tTest accuracy:\t', scores[1])
Y_pred = model.predict(x_test, verbose=2)
cm = confusion_matrix(np.argmax(y_test,axis=1),np.argmax(Y_pred, axis=1))
print('\tConfusion Matrix:\t')
print(cm)


  - Base case:
	Test loss:	 0.8805189178466797
	Test accuracy:	 0.6913
	Confusion Matrix:	
[[761  22  42  12   7   6  12  18  65  55]
 [ 17 829   5   4   1   2  12   8  15 107]
 [ 80  10 524  54  93  66  80  61  11  21]
 [ 20  15  72 413  70 200  89  72  18  31]
 [ 30   6  83  34 553  40  87 148  14   5]
 [  9   2  52 121  52 607  39  88  12  18]
 [  9   4  41  43  38  20 812  17   7   9]
 [ 13   6  25  18  39  53  10 817   3  16]
 [ 78  59  15   7   4   6   7   9 775  40]
 [ 34  69   4   7   6   4  11  23  20 822]]


### 1) Augment the data by adding noise.

In [15]:
# Save models with gaussian noise with different Standard Deviation
for e in [0.5,0.1,0.05,0.02,0.01]:  
  model = Sequential()
  model.add(Conv2D(32, (3, 3), padding='same',input_shape=x_train.shape[1:]))
  model.add(Activation('relu'))
  model.add(Conv2D(32, (3, 3)))
  model.add(Activation('relu'))
  model.add(MaxPooling2D(pool_size=(2, 2)))
  model.add(Dropout(0.25))
  
  #Add noise
  model.add(keras.layers.GaussianNoise(e))

  model.add(Conv2D(64, (3, 3), padding='same'))
  model.add(Activation('relu'))
  model.add(Conv2D(64, (3, 3)))
  model.add(Activation('relu'))
  model.add(MaxPooling2D(pool_size=(2, 2)))
  model.add(Dropout(0.25))

  model.add(Flatten())
  model.add(Dense(512))
  model.add(Activation('relu'))
  model.add(Dropout(0.5))
  model.add(Dense(num_classes))
  model.add(Activation('softmax'))
  
  model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])
  model.fit(x_train, y_train,
                batch_size=batch_size,
                epochs=epochs,
                validation_data=(x_test, y_test),
                shuffle=True)
  model.save('cifra10_n'+str(e)+'.h5')

Train on 50000 samples, validate on 10000 samples
Epoch 1/20
50000/50000 [==============================] - 14s 274us/step - loss: 2.2335 - acc: 0.1548 - val_loss: 2.3352 - val_acc: 0.1054
Epoch 2/20
50000/50000 [==============================] - 13s 262us/step - loss: 2.0171 - acc: 0.2517 - val_loss: 2.1543 - val_acc: 0.1526
Epoch 3/20
 8576/50000 [====>.........................] - ETA: 10s - loss: 1.9442 - acc: 0.2912

50000/50000 [==============================] - 13s 261us/step - loss: 1.8772 - acc: 0.3123 - val_loss: 2.0207 - val_acc: 0.2273
Epoch 4/20
50000/50000 [==============================] - 13s 262us/step - loss: 1.7720 - acc: 0.3539 - val_loss: 1.9886 - val_acc: 0.2551
Epoch 5/20
29312/50000 [================>.............] - ETA: 5s - loss: 1.7016 - acc: 0.3826

50000/50000 [==============================] - 13s 263us/step - loss: 1.6924 - acc: 0.3856 - val_loss: 1.8913 - val_acc: 0.3243
Epoch 6/20
50000/50000 [==============================] - 13s 261us/step - loss: 1.6389 - acc: 0.4035 - val_loss: 1.8533 - val_acc: 0.3422
Epoch 7/20
34432/50000 [===================>..........] - ETA: 3s - loss: 1.5922 - acc: 0.4223

50000/50000 [==============================] - 13s 264us/step - loss: 1.5881 - acc: 0.4241 - val_loss: 1.7911 - val_acc: 0.3763
Epoch 8/20
50000/50000 [==============================] - 13s 264us/step - loss: 1.5424 - acc: 0.4418 - val_loss: 1.7739 - val_acc: 0.3802
Epoch 9/20
34688/50000 [===================>..........] - ETA: 3s - loss: 1.5112 - acc: 0.4572

50000/50000 [==============================] - 13s 258us/step - loss: 1.5094 - acc: 0.4568 - val_loss: 1.7013 - val_acc: 0.4053
Epoch 10/20
50000/50000 [==============================] - 13s 264us/step - loss: 1.4753 - acc: 0.4683 - val_loss: 1.8071 - val_acc: 0.3824
Epoch 11/20
34944/50000 [===================>..........] - ETA: 3s - loss: 1.4407 - acc: 0.4804

50000/50000 [==============================] - 13s 262us/step - loss: 1.4412 - acc: 0.4814 - val_loss: 1.7206 - val_acc: 0.4017
Epoch 12/20
50000/50000 [==============================] - 13s 260us/step - loss: 1.4142 - acc: 0.4917 - val_loss: 1.6308 - val_acc: 0.4261
Epoch 13/20
35200/50000 [====================>.........] - ETA: 3s - loss: 1.3855 - acc: 0.5019

50000/50000 [==============================] - 13s 263us/step - loss: 1.3845 - acc: 0.5031 - val_loss: 1.6744 - val_acc: 0.4259
Epoch 14/20
50000/50000 [==============================] - 13s 259us/step - loss: 1.3606 - acc: 0.5128 - val_loss: 1.6078 - val_acc: 0.4414
Epoch 15/20
35968/50000 [====================>.........] - ETA: 3s - loss: 1.3458 - acc: 0.5192

50000/50000 [==============================] - 13s 261us/step - loss: 1.3380 - acc: 0.5216 - val_loss: 1.4557 - val_acc: 0.4826
Epoch 16/20
50000/50000 [==============================] - 13s 263us/step - loss: 1.3169 - acc: 0.5286 - val_loss: 1.6442 - val_acc: 0.4408
Epoch 17/20
35712/50000 [====================>.........] - ETA: 3s - loss: 1.2976 - acc: 0.5358

50000/50000 [==============================] - 13s 261us/step - loss: 1.2986 - acc: 0.5363 - val_loss: 1.5048 - val_acc: 0.4745
Epoch 18/20
50000/50000 [==============================] - 13s 265us/step - loss: 1.2789 - acc: 0.5434 - val_loss: 1.4914 - val_acc: 0.4804
Epoch 19/20
34688/50000 [===================>..........] - ETA: 3s - loss: 1.2568 - acc: 0.5518

50000/50000 [==============================] - 13s 260us/step - loss: 1.2605 - acc: 0.5518 - val_loss: 1.3974 - val_acc: 0.5087
Epoch 20/20
50000/50000 [==============================] - 13s 260us/step - loss: 1.2410 - acc: 0.5583 - val_loss: 1.4773 - val_acc: 0.4864
Train on 50000 samples, validate on 10000 samples
Epoch 1/20
29824/50000 [================>.............] - ETA: 5s - loss: 2.1255 - acc: 0.2029

50000/50000 [==============================] - 14s 275us/step - loss: 2.0457 - acc: 0.2415 - val_loss: 1.8455 - val_acc: 0.3427
Epoch 2/20
50000/50000 [==============================] - 13s 262us/step - loss: 1.7601 - acc: 0.3619 - val_loss: 1.6675 - val_acc: 0.4057
Epoch 3/20
33920/50000 [===================>..........] - ETA: 3s - loss: 1.6573 - acc: 0.3999

50000/50000 [==============================] - 13s 262us/step - loss: 1.6447 - acc: 0.4039 - val_loss: 1.5887 - val_acc: 0.4240
Epoch 4/20
50000/50000 [==============================] - 13s 261us/step - loss: 1.5544 - acc: 0.4363 - val_loss: 1.4892 - val_acc: 0.4646
Epoch 5/20
35456/50000 [====================>.........] - ETA: 3s - loss: 1.4854 - acc: 0.4629

50000/50000 [==============================] - 13s 262us/step - loss: 1.4808 - acc: 0.4658 - val_loss: 1.4487 - val_acc: 0.4810
Epoch 6/20
50000/50000 [==============================] - 13s 265us/step - loss: 1.4285 - acc: 0.4887 - val_loss: 1.4188 - val_acc: 0.4913
Epoch 7/20
35200/50000 [====================>.........] - ETA: 3s - loss: 1.3917 - acc: 0.5006

50000/50000 [==============================] - 13s 258us/step - loss: 1.3817 - acc: 0.5043 - val_loss: 1.3623 - val_acc: 0.5155
Epoch 8/20
50000/50000 [==============================] - 13s 259us/step - loss: 1.3364 - acc: 0.5227 - val_loss: 1.2926 - val_acc: 0.5400
Epoch 9/20
34688/50000 [===================>..........] - ETA: 3s - loss: 1.3094 - acc: 0.5330

50000/50000 [==============================] - 13s 264us/step - loss: 1.3033 - acc: 0.5361 - val_loss: 1.2663 - val_acc: 0.5525
Epoch 10/20
50000/50000 [==============================] - 13s 262us/step - loss: 1.2689 - acc: 0.5465 - val_loss: 1.2783 - val_acc: 0.5478
Epoch 11/20
35200/50000 [====================>.........] - ETA: 3s - loss: 1.2438 - acc: 0.5589

50000/50000 [==============================] - 13s 264us/step - loss: 1.2356 - acc: 0.5621 - val_loss: 1.1531 - val_acc: 0.5881
Epoch 12/20
50000/50000 [==============================] - 13s 260us/step - loss: 1.2066 - acc: 0.5730 - val_loss: 1.1543 - val_acc: 0.5895
Epoch 13/20
35200/50000 [====================>.........] - ETA: 3s - loss: 1.1716 - acc: 0.5870

50000/50000 [==============================] - 13s 262us/step - loss: 1.1732 - acc: 0.5864 - val_loss: 1.1322 - val_acc: 0.6012
Epoch 14/20
50000/50000 [==============================] - 13s 264us/step - loss: 1.1485 - acc: 0.5945 - val_loss: 1.0787 - val_acc: 0.6241
Epoch 15/20
35200/50000 [====================>.........] - ETA: 3s - loss: 1.1280 - acc: 0.6012

50000/50000 [==============================] - 13s 262us/step - loss: 1.1260 - acc: 0.6026 - val_loss: 1.0543 - val_acc: 0.6339
Epoch 16/20
50000/50000 [==============================] - 13s 262us/step - loss: 1.0977 - acc: 0.6124 - val_loss: 1.0388 - val_acc: 0.6383
Epoch 17/20
34944/50000 [===================>..........] - ETA: 3s - loss: 1.0810 - acc: 0.6192

50000/50000 [==============================] - 13s 261us/step - loss: 1.0781 - acc: 0.6201 - val_loss: 1.0365 - val_acc: 0.6374
Epoch 18/20
50000/50000 [==============================] - 13s 260us/step - loss: 1.0549 - acc: 0.6291 - val_loss: 0.9921 - val_acc: 0.6541
Epoch 19/20
35200/50000 [====================>.........] - ETA: 3s - loss: 1.0359 - acc: 0.6379

50000/50000 [==============================] - 13s 262us/step - loss: 1.0335 - acc: 0.6375 - val_loss: 0.9881 - val_acc: 0.6573
Epoch 20/20
50000/50000 [==============================] - 13s 262us/step - loss: 1.0111 - acc: 0.6451 - val_loss: 0.9551 - val_acc: 0.6693
Train on 50000 samples, validate on 10000 samples
Epoch 1/20
30848/50000 [=================>............] - ETA: 5s - loss: 2.0371 - acc: 0.2472

50000/50000 [==============================] - 14s 283us/step - loss: 1.9401 - acc: 0.2874 - val_loss: 1.7217 - val_acc: 0.3886
Epoch 2/20
50000/50000 [==============================] - 13s 262us/step - loss: 1.6799 - acc: 0.3870 - val_loss: 1.5525 - val_acc: 0.4375
Epoch 3/20
34688/50000 [===================>..........] - ETA: 3s - loss: 1.5917 - acc: 0.4203

50000/50000 [==============================] - 13s 262us/step - loss: 1.5790 - acc: 0.4257 - val_loss: 1.4774 - val_acc: 0.4592
Epoch 4/20
50000/50000 [==============================] - 13s 265us/step - loss: 1.4991 - acc: 0.4533 - val_loss: 1.4126 - val_acc: 0.4861
Epoch 5/20
34432/50000 [===================>..........] - ETA: 3s - loss: 1.4454 - acc: 0.4758

50000/50000 [==============================] - 13s 264us/step - loss: 1.4403 - acc: 0.4790 - val_loss: 1.3540 - val_acc: 0.5067
Epoch 6/20
50000/50000 [==============================] - 13s 261us/step - loss: 1.3967 - acc: 0.4959 - val_loss: 1.3593 - val_acc: 0.5197
Epoch 7/20
35456/50000 [====================>.........] - ETA: 3s - loss: 1.3473 - acc: 0.5144

50000/50000 [==============================] - 13s 262us/step - loss: 1.3490 - acc: 0.5164 - val_loss: 1.2903 - val_acc: 0.5375
Epoch 8/20
50000/50000 [==============================] - 13s 263us/step - loss: 1.3143 - acc: 0.5310 - val_loss: 1.2266 - val_acc: 0.5679
Epoch 9/20
35712/50000 [====================>.........] - ETA: 3s - loss: 1.2828 - acc: 0.5418

50000/50000 [==============================] - 13s 263us/step - loss: 1.2810 - acc: 0.5426 - val_loss: 1.2041 - val_acc: 0.5708
Epoch 10/20
50000/50000 [==============================] - 13s 261us/step - loss: 1.2525 - acc: 0.5554 - val_loss: 1.2142 - val_acc: 0.5668
Epoch 11/20
35200/50000 [====================>.........] - ETA: 3s - loss: 1.2187 - acc: 0.5679

50000/50000 [==============================] - 13s 259us/step - loss: 1.2176 - acc: 0.5695 - val_loss: 1.1579 - val_acc: 0.5876
Epoch 12/20
50000/50000 [==============================] - 13s 263us/step - loss: 1.1890 - acc: 0.5781 - val_loss: 1.1244 - val_acc: 0.6049
Epoch 13/20
32896/50000 [==================>...........] - ETA: 4s - loss: 1.1657 - acc: 0.5865

50000/50000 [==============================] - 13s 265us/step - loss: 1.1660 - acc: 0.5872 - val_loss: 1.1268 - val_acc: 0.6032
Epoch 14/20
50000/50000 [==============================] - 13s 259us/step - loss: 1.1362 - acc: 0.6027 - val_loss: 1.1349 - val_acc: 0.5975
Epoch 15/20
34688/50000 [===================>..........] - ETA: 3s - loss: 1.1124 - acc: 0.6082

50000/50000 [==============================] - 13s 260us/step - loss: 1.1136 - acc: 0.6078 - val_loss: 1.0264 - val_acc: 0.6452
Epoch 16/20
50000/50000 [==============================] - 13s 266us/step - loss: 1.0897 - acc: 0.6181 - val_loss: 1.1338 - val_acc: 0.6008
Epoch 17/20
32896/50000 [==================>...........] - ETA: 4s - loss: 1.0693 - acc: 0.6224

50000/50000 [==============================] - 13s 265us/step - loss: 1.0615 - acc: 0.6252 - val_loss: 1.0465 - val_acc: 0.6334
Epoch 18/20
50000/50000 [==============================] - 13s 262us/step - loss: 1.0469 - acc: 0.6338 - val_loss: 0.9767 - val_acc: 0.6631
Epoch 19/20
34432/50000 [===================>..........] - ETA: 3s - loss: 1.0224 - acc: 0.6393

50000/50000 [==============================] - 13s 262us/step - loss: 1.0222 - acc: 0.6413 - val_loss: 0.9576 - val_acc: 0.6705
Epoch 20/20
50000/50000 [==============================] - 13s 261us/step - loss: 1.0071 - acc: 0.6495 - val_loss: 0.9679 - val_acc: 0.6651
Train on 50000 samples, validate on 10000 samples
Epoch 1/20
30848/50000 [=================>............] - ETA: 5s - loss: 2.0750 - acc: 0.2321

50000/50000 [==============================] - 14s 280us/step - loss: 1.9714 - acc: 0.2771 - val_loss: 1.6845 - val_acc: 0.4059
Epoch 2/20
50000/50000 [==============================] - 13s 267us/step - loss: 1.6638 - acc: 0.3952 - val_loss: 1.5466 - val_acc: 0.4403
Epoch 3/20
34688/50000 [===================>..........] - ETA: 3s - loss: 1.5573 - acc: 0.4367

50000/50000 [==============================] - 13s 262us/step - loss: 1.5461 - acc: 0.4414 - val_loss: 1.4363 - val_acc: 0.4851
Epoch 4/20
50000/50000 [==============================] - 13s 263us/step - loss: 1.4758 - acc: 0.4656 - val_loss: 1.4092 - val_acc: 0.4898
Epoch 5/20
35456/50000 [====================>.........] - ETA: 3s - loss: 1.4256 - acc: 0.4869

50000/50000 [==============================] - 13s 262us/step - loss: 1.4179 - acc: 0.4911 - val_loss: 1.3168 - val_acc: 0.5317
Epoch 6/20
50000/50000 [==============================] - 13s 262us/step - loss: 1.3722 - acc: 0.5066 - val_loss: 1.3052 - val_acc: 0.5327
Epoch 7/20
35456/50000 [====================>.........] - ETA: 3s - loss: 1.3336 - acc: 0.5217

50000/50000 [==============================] - 13s 263us/step - loss: 1.3270 - acc: 0.5245 - val_loss: 1.3002 - val_acc: 0.5435
Epoch 8/20
50000/50000 [==============================] - 13s 263us/step - loss: 1.2900 - acc: 0.5362 - val_loss: 1.2621 - val_acc: 0.5579
Epoch 9/20
34688/50000 [===================>..........] - ETA: 3s - loss: 1.2523 - acc: 0.5573

50000/50000 [==============================] - 13s 263us/step - loss: 1.2517 - acc: 0.5573 - val_loss: 1.1753 - val_acc: 0.5839
Epoch 10/20
50000/50000 [==============================] - 13s 263us/step - loss: 1.2208 - acc: 0.5647 - val_loss: 1.1335 - val_acc: 0.6046
Epoch 11/20
34944/50000 [===================>..........] - ETA: 3s - loss: 1.1892 - acc: 0.5804

50000/50000 [==============================] - 13s 261us/step - loss: 1.1906 - acc: 0.5807 - val_loss: 1.1345 - val_acc: 0.6029
Epoch 12/20
50000/50000 [==============================] - 13s 265us/step - loss: 1.1600 - acc: 0.5901 - val_loss: 1.0933 - val_acc: 0.6194
Epoch 13/20
34944/50000 [===================>..........] - ETA: 3s - loss: 1.1347 - acc: 0.5962

50000/50000 [==============================] - 13s 262us/step - loss: 1.1316 - acc: 0.5980 - val_loss: 1.0730 - val_acc: 0.6190
Epoch 14/20
50000/50000 [==============================] - 13s 262us/step - loss: 1.1028 - acc: 0.6099 - val_loss: 1.0245 - val_acc: 0.6429
Epoch 15/20
33664/50000 [===================>..........] - ETA: 4s - loss: 1.0831 - acc: 0.6182

50000/50000 [==============================] - 13s 265us/step - loss: 1.0808 - acc: 0.6187 - val_loss: 1.0396 - val_acc: 0.6353
Epoch 16/20
50000/50000 [==============================] - 13s 264us/step - loss: 1.0567 - acc: 0.6282 - val_loss: 1.0027 - val_acc: 0.6492
Epoch 17/20
34688/50000 [===================>..........] - ETA: 3s - loss: 1.0367 - acc: 0.6383

50000/50000 [==============================] - 13s 261us/step - loss: 1.0361 - acc: 0.6366 - val_loss: 0.9714 - val_acc: 0.6637
Epoch 18/20
50000/50000 [==============================] - 13s 261us/step - loss: 1.0124 - acc: 0.6434 - val_loss: 0.9511 - val_acc: 0.6728
Epoch 19/20
35200/50000 [====================>.........] - ETA: 3s - loss: 0.9933 - acc: 0.6513

50000/50000 [==============================] - 13s 262us/step - loss: 0.9940 - acc: 0.6513 - val_loss: 0.9575 - val_acc: 0.6674
Epoch 20/20
50000/50000 [==============================] - 13s 267us/step - loss: 0.9753 - acc: 0.6568 - val_loss: 0.9284 - val_acc: 0.6798
Train on 50000 samples, validate on 10000 samples
Epoch 1/20
29824/50000 [================>.............] - ETA: 5s - loss: 2.0924 - acc: 0.2257

50000/50000 [==============================] - 14s 281us/step - loss: 1.9951 - acc: 0.2675 - val_loss: 1.7247 - val_acc: 0.3927
Epoch 2/20
50000/50000 [==============================] - 13s 261us/step - loss: 1.7004 - acc: 0.3839 - val_loss: 1.5706 - val_acc: 0.4359
Epoch 3/20
33920/50000 [===================>..........] - ETA: 4s - loss: 1.6002 - acc: 0.4169

50000/50000 [==============================] - 13s 265us/step - loss: 1.5839 - acc: 0.4225 - val_loss: 1.4859 - val_acc: 0.4624
Epoch 4/20
50000/50000 [==============================] - 13s 262us/step - loss: 1.5057 - acc: 0.4546 - val_loss: 1.4534 - val_acc: 0.4781
Epoch 5/20
35456/50000 [====================>.........] - ETA: 3s - loss: 1.4446 - acc: 0.4777

50000/50000 [==============================] - 13s 265us/step - loss: 1.4425 - acc: 0.4784 - val_loss: 1.3593 - val_acc: 0.5143
Epoch 6/20
50000/50000 [==============================] - 13s 263us/step - loss: 1.3927 - acc: 0.4969 - val_loss: 1.3141 - val_acc: 0.5317
Epoch 7/20
35456/50000 [====================>.........] - ETA: 3s - loss: 1.3519 - acc: 0.5160

50000/50000 [==============================] - 13s 262us/step - loss: 1.3435 - acc: 0.5188 - val_loss: 1.2560 - val_acc: 0.5565
Epoch 8/20
50000/50000 [==============================] - 13s 265us/step - loss: 1.3024 - acc: 0.5362 - val_loss: 1.2401 - val_acc: 0.5594
Epoch 9/20
35456/50000 [====================>.........] - ETA: 3s - loss: 1.2642 - acc: 0.5517

50000/50000 [==============================] - 13s 261us/step - loss: 1.2611 - acc: 0.5525 - val_loss: 1.2008 - val_acc: 0.5792
Epoch 10/20
50000/50000 [==============================] - 13s 263us/step - loss: 1.2258 - acc: 0.5640 - val_loss: 1.1561 - val_acc: 0.5970
Epoch 11/20
34688/50000 [===================>..........] - ETA: 3s - loss: 1.1950 - acc: 0.5771

50000/50000 [==============================] - 13s 264us/step - loss: 1.1925 - acc: 0.5790 - val_loss: 1.1301 - val_acc: 0.6029
Epoch 12/20
50000/50000 [==============================] - 13s 261us/step - loss: 1.1613 - acc: 0.5894 - val_loss: 1.0997 - val_acc: 0.6126
Epoch 13/20
34944/50000 [===================>..........] - ETA: 3s - loss: 1.1347 - acc: 0.5995

50000/50000 [==============================] - 13s 264us/step - loss: 1.1308 - acc: 0.6006 - val_loss: 1.0674 - val_acc: 0.6258
Epoch 14/20
50000/50000 [==============================] - 13s 262us/step - loss: 1.1002 - acc: 0.6116 - val_loss: 1.0521 - val_acc: 0.6326
Epoch 15/20
35200/50000 [====================>.........] - ETA: 3s - loss: 1.0822 - acc: 0.6188

50000/50000 [==============================] - 13s 262us/step - loss: 1.0779 - acc: 0.6199 - val_loss: 1.0421 - val_acc: 0.6392
Epoch 16/20
50000/50000 [==============================] - 13s 266us/step - loss: 1.0501 - acc: 0.6301 - val_loss: 0.9951 - val_acc: 0.6536
Epoch 17/20
34432/50000 [===================>..........] - ETA: 3s - loss: 1.0334 - acc: 0.6342

50000/50000 [==============================] - 13s 263us/step - loss: 1.0299 - acc: 0.6369 - val_loss: 0.9784 - val_acc: 0.6591
Epoch 18/20
50000/50000 [==============================] - 13s 263us/step - loss: 1.0097 - acc: 0.6455 - val_loss: 0.9454 - val_acc: 0.6685
Epoch 19/20
35456/50000 [====================>.........] - ETA: 3s - loss: 0.9882 - acc: 0.6516

50000/50000 [==============================] - 13s 264us/step - loss: 0.9884 - acc: 0.6526 - val_loss: 0.9232 - val_acc: 0.6795
Epoch 20/20
50000/50000 [==============================] - 13s 262us/step - loss: 0.9676 - acc: 0.6610 - val_loss: 0.8999 - val_acc: 0.6857


In [16]:
# Load models and print results
for e in [0.5,0.1,0.05,0.02,0.01]:
    model = keras.models.load_model('cifra10_n'+str(e)+'.h5')
    print('\n  - Gaussian Noise with '+str(e)+' stdev:')
    scores = model.evaluate(x_test, y_test, verbose=0)
    print('\tTest loss:\t', scores[0])
    print('\tTest accuracy:\t', scores[1])


  - Gaussian Noise with 0.5 stdev:
	Test loss:	 1.4772556245803834
	Test accuracy:	 0.4864

  - Gaussian Noise with 0.1 stdev:
	Test loss:	 0.9550858486175537
	Test accuracy:	 0.6693

  - Gaussian Noise with 0.05 stdev:
	Test loss:	 0.9679321733474732
	Test accuracy:	 0.6651

  - Gaussian Noise with 0.02 stdev:
	Test loss:	 0.9283743391036987
	Test accuracy:	 0.6798

  - Gaussian Noise with 0.01 stdev:
	Test loss:	 0.8998800125122071
	Test accuracy:	 0.6857


### 2) Add layers to the network to improve performance

#### A) Add more layers and Adam optimizer

In [17]:
model = Sequential()

model.add(Conv2D(32, (3, 3), padding='same',
                 input_shape=x_train.shape[1:]))
model.add(Activation('relu'))
model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(64, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(512))
#add another dense layer
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy',optimizer=keras.optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False),metrics=['accuracy'])
model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_data=(x_test, y_test), shuffle=True)

print('\n  - More layers and Atom optimizer:')
scores = model.evaluate(x_test, y_test, verbose=0)
print('\tTest loss:\t', scores[0])
print('\tTest accuracy:\t', scores[1])

Y_pred = model.predict(x_test, verbose=2)
cm = confusion_matrix(np.argmax(y_test,axis=1),np.argmax(Y_pred, axis=1))
print('\tConfusion Matrix:\t')
print(cm)

Train on 50000 samples, validate on 10000 samples
Epoch 1/20
50000/50000 [==============================] - 16s 312us/step - loss: 1.5690 - acc: 0.4235 - val_loss: 1.1981 - val_acc: 0.5662
Epoch 2/20
50000/50000 [==============================] - 14s 282us/step - loss: 1.1358 - acc: 0.5948 - val_loss: 0.9637 - val_acc: 0.6553
Epoch 3/20
 6016/50000 [==>...........................] - ETA: 11s - loss: 0.9922 - acc: 0.6444

50000/50000 [==============================] - 14s 277us/step - loss: 0.9671 - acc: 0.6579 - val_loss: 0.8512 - val_acc: 0.7000
Epoch 4/20
50000/50000 [==============================] - 14s 278us/step - loss: 0.8671 - acc: 0.6934 - val_loss: 0.7820 - val_acc: 0.7274
Epoch 5/20
24448/50000 [=============>................] - ETA: 6s - loss: 0.8088 - acc: 0.7172

50000/50000 [==============================] - 14s 279us/step - loss: 0.8141 - acc: 0.7145 - val_loss: 0.7407 - val_acc: 0.7419
Epoch 6/20
50000/50000 [==============================] - 14s 275us/step - loss: 0.7706 - acc: 0.7298 - val_loss: 0.7394 - val_acc: 0.7418
Epoch 7/20
29568/50000 [================>.............] - ETA: 5s - loss: 0.7231 - acc: 0.7455

50000/50000 [==============================] - 14s 281us/step - loss: 0.7287 - acc: 0.7425 - val_loss: 0.7195 - val_acc: 0.7527
Epoch 8/20
50000/50000 [==============================] - 14s 277us/step - loss: 0.7058 - acc: 0.7523 - val_loss: 0.6805 - val_acc: 0.7647
Epoch 9/20
30592/50000 [=================>............] - ETA: 5s - loss: 0.6598 - acc: 0.7648

50000/50000 [==============================] - 14s 279us/step - loss: 0.6700 - acc: 0.7634 - val_loss: 0.6765 - val_acc: 0.7706
Epoch 10/20
50000/50000 [==============================] - 14s 279us/step - loss: 0.6467 - acc: 0.7724 - val_loss: 0.6806 - val_acc: 0.7715
Epoch 11/20
28288/50000 [===============>..............] - ETA: 5s - loss: 0.6236 - acc: 0.7780

50000/50000 [==============================] - 14s 277us/step - loss: 0.6319 - acc: 0.7767 - val_loss: 0.6731 - val_acc: 0.7672
Epoch 12/20
50000/50000 [==============================] - 14s 280us/step - loss: 0.6133 - acc: 0.7858 - val_loss: 0.6516 - val_acc: 0.7768
Epoch 13/20
29568/50000 [================>.............] - ETA: 5s - loss: 0.5923 - acc: 0.7900

50000/50000 [==============================] - 14s 277us/step - loss: 0.5999 - acc: 0.7872 - val_loss: 0.6653 - val_acc: 0.7810
Epoch 14/20
50000/50000 [==============================] - 14s 281us/step - loss: 0.5760 - acc: 0.7956 - val_loss: 0.6374 - val_acc: 0.7828
Epoch 15/20
31616/50000 [=================>............] - ETA: 4s - loss: 0.5571 - acc: 0.8036

50000/50000 [==============================] - 14s 275us/step - loss: 0.5649 - acc: 0.8012 - val_loss: 0.6578 - val_acc: 0.7814
Epoch 16/20
50000/50000 [==============================] - 14s 277us/step - loss: 0.5562 - acc: 0.8022 - val_loss: 0.6352 - val_acc: 0.7899
Epoch 17/20
32128/50000 [==================>...........] - ETA: 4s - loss: 0.5232 - acc: 0.8138

50000/50000 [==============================] - 14s 280us/step - loss: 0.5293 - acc: 0.8115 - val_loss: 0.6192 - val_acc: 0.7893
Epoch 18/20
50000/50000 [==============================] - 14s 278us/step - loss: 0.5359 - acc: 0.8112 - val_loss: 0.6386 - val_acc: 0.7858
Epoch 19/20
30080/50000 [=================>............] - ETA: 5s - loss: 0.5115 - acc: 0.8201

50000/50000 [==============================] - 14s 281us/step - loss: 0.5246 - acc: 0.8154 - val_loss: 0.6540 - val_acc: 0.7834
Epoch 20/20
50000/50000 [==============================] - 14s 279us/step - loss: 0.5094 - acc: 0.8202 - val_loss: 0.6470 - val_acc: 0.7883

  - More layers and Atom optimizer:
	Test loss:	 0.6469792132854462
	Test accuracy:	 0.7883
	Confusion Matrix:	
[[832  15  43   9  14   1  10  12  42  22]
 [  8 911   4   0   1   2   9   2  13  50]
 [ 59   6 696  29  38  49  78  31   9   5]
 [ 19   6  83 513  46 160 110  33  19  11]
 [ 13   4  76  36 695  30 103  34   7   2]
 [ 10   2  55 101  26 723  38  36   2   7]
 [  6   0  27  17  11   8 921   4   5   1]
 [ 11   3  33  21  36  31  10 848   2   5]
 [ 51  17   5   8   5   3   7   5 878  21]
 [ 21  58   5  10   2   1   8  10  19 866]]


#### B) Use batch normalization

In [18]:
from keras.layers.normalization import BatchNormalization

model = Sequential()
model.add(Conv2D(32, (3, 3), padding='same',input_shape=x_train.shape[1:]))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Conv2D(32, (3, 3)))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Conv2D(64, (3, 3), padding='same'))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Conv2D(64, (3, 3)))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes))
model.add(Activation('softmax'))

opt = keras.optimizers.rmsprop(lr=0.0001, decay=1e-6)
model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])
model.fit(x_train, y_train,batch_size=batch_size, epochs=epochs, validation_data=(x_test, y_test), shuffle=True)

print('\n  - Model with Batch Normalization:')
scores = model.evaluate(x_test, y_test, verbose=0)
print('\tTest loss:\t', scores[0])
print('\tTest accuracy:\t', scores[1])

Y_pred = model.predict(x_test, verbose=2)
cm = confusion_matrix(np.argmax(y_test,axis=1),np.argmax(Y_pred, axis=1))
print('\tConfusion Matrix:\t')
print(cm)

Train on 50000 samples, validate on 10000 samples
Epoch 1/20
50000/50000 [==============================] - 20s 397us/step - loss: 1.9795 - acc: 0.2991 - val_loss: 1.5757 - val_acc: 0.4343
Epoch 2/20
50000/50000 [==============================] - 18s 353us/step - loss: 1.5930 - acc: 0.4184 - val_loss: 1.3964 - val_acc: 0.4975
Epoch 3/20
 8576/50000 [====>.........................] - ETA: 13s - loss: 1.4962 - acc: 0.4556

50000/50000 [==============================] - 18s 355us/step - loss: 1.4592 - acc: 0.4710 - val_loss: 1.2724 - val_acc: 0.5441
Epoch 4/20
50000/50000 [==============================] - 18s 352us/step - loss: 1.3706 - acc: 0.5075 - val_loss: 1.1969 - val_acc: 0.5686
Epoch 5/20
29568/50000 [================>.............] - ETA: 6s - loss: 1.3087 - acc: 0.5310

50000/50000 [==============================] - 18s 353us/step - loss: 1.3013 - acc: 0.5337 - val_loss: 1.1699 - val_acc: 0.5794
Epoch 6/20
50000/50000 [==============================] - 18s 353us/step - loss: 1.2426 - acc: 0.5545 - val_loss: 1.1738 - val_acc: 0.5741
Epoch 7/20
33792/50000 [===================>..........] - ETA: 5s - loss: 1.1974 - acc: 0.5716

50000/50000 [==============================] - 18s 355us/step - loss: 1.1860 - acc: 0.5766 - val_loss: 1.0587 - val_acc: 0.6205
Epoch 8/20
50000/50000 [==============================] - 18s 353us/step - loss: 1.1392 - acc: 0.5953 - val_loss: 1.1156 - val_acc: 0.5990
Epoch 9/20
34304/50000 [===================>..........] - ETA: 5s - loss: 1.0940 - acc: 0.6095

50000/50000 [==============================] - 18s 352us/step - loss: 1.0912 - acc: 0.6107 - val_loss: 1.0623 - val_acc: 0.6267
Epoch 10/20
50000/50000 [==============================] - 17s 350us/step - loss: 1.0429 - acc: 0.6293 - val_loss: 1.0198 - val_acc: 0.6306
Epoch 11/20
35328/50000 [====================>.........] - ETA: 4s - loss: 1.0103 - acc: 0.6401

50000/50000 [==============================] - 18s 356us/step - loss: 1.0048 - acc: 0.6407 - val_loss: 0.9051 - val_acc: 0.6790
Epoch 12/20
50000/50000 [==============================] - 18s 351us/step - loss: 0.9707 - acc: 0.6530 - val_loss: 0.8595 - val_acc: 0.6914
Epoch 13/20
34688/50000 [===================>..........] - ETA: 5s - loss: 0.9357 - acc: 0.6658

50000/50000 [==============================] - 18s 355us/step - loss: 0.9374 - acc: 0.6665 - val_loss: 0.8569 - val_acc: 0.6986
Epoch 14/20
50000/50000 [==============================] - 18s 353us/step - loss: 0.9116 - acc: 0.6773 - val_loss: 0.8801 - val_acc: 0.6903
Epoch 15/20
34944/50000 [===================>..........] - ETA: 4s - loss: 0.8841 - acc: 0.6884

50000/50000 [==============================] - 18s 355us/step - loss: 0.8804 - acc: 0.6890 - val_loss: 0.9000 - val_acc: 0.6813
Epoch 16/20
50000/50000 [==============================] - 18s 353us/step - loss: 0.8579 - acc: 0.6972 - val_loss: 0.8400 - val_acc: 0.7050
Epoch 17/20
34944/50000 [===================>..........] - ETA: 5s - loss: 0.8424 - acc: 0.7040

50000/50000 [==============================] - 18s 356us/step - loss: 0.8356 - acc: 0.7057 - val_loss: 0.8238 - val_acc: 0.7097
Epoch 18/20
50000/50000 [==============================] - 18s 357us/step - loss: 0.8095 - acc: 0.7142 - val_loss: 0.7941 - val_acc: 0.7213
Epoch 19/20
34688/50000 [===================>..........] - ETA: 5s - loss: 0.7919 - acc: 0.7231

50000/50000 [==============================] - 18s 355us/step - loss: 0.7952 - acc: 0.7209 - val_loss: 0.7472 - val_acc: 0.7359
Epoch 20/20
50000/50000 [==============================] - 18s 354us/step - loss: 0.7769 - acc: 0.7238 - val_loss: 0.7987 - val_acc: 0.7221

  - Model with Batch Normalization:
	Test loss:	 0.7986920112609863
	Test accuracy:	 0.7221
	Confusion Matrix:	
[[666   9  47  59  37  12  11  11  90  58]
 [ 10 769   7  22   9   6  23   5  44 105]
 [ 44   1 503 118 101 105  92  23   8   5]
 [  7   0  28 641  45 204  52  11   8   4]
 [  7   0  34 122 679  59  54  37   7   1]
 [  4   0  19 188  32 714  13  27   2   1]
 [  2   1  19  89  31  24 829   4   1   0]
 [  5   1  19  57  74 127  10 701   2   4]
 [ 23  13   5  35   7   8   7   0 881  21]
 [ 13  35   8  34   9   7  13  12  31 838]]


### 3) Try another method batch normalization to deal with overfitting 

#### Using Regularizer

In [19]:
from keras import regularizers

weight_decay = 1e-4
model = Sequential()
model.add(Conv2D(32, (3, 3), padding='same', input_shape=x_train.shape[1:]))

model.add(Activation('relu'))
model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(64, (3, 3), padding='same', kernel_regularizer=regularizers.l2(weight_decay)))
model.add(Activation('relu'))
model.add(Conv2D(64, (3, 3), kernel_regularizer=regularizers.l2(weight_decay)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes))
model.add(Activation('softmax'))

opt = keras.optimizers.rmsprop(lr=0.0001, decay=1e-6)
model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])
model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_data=(x_test, y_test), shuffle=True)

print('\n  - regularizer L2:')
scores = model.evaluate(x_test, y_test, verbose=0)
print('\tTest loss:\t', scores[0])
print('\tTest accuracy:\t', scores[1])
Y_pred = model.predict(x_test, verbose=2)
cm = confusion_matrix(np.argmax(y_test,axis=1),np.argmax(Y_pred, axis=1))
print('\tConfusion Matrix:\t')
print(cm)

Train on 50000 samples, validate on 10000 samples
Epoch 1/20
50000/50000 [==============================] - 15s 298us/step - loss: 1.9566 - acc: 0.2847 - val_loss: 1.6900 - val_acc: 0.3984
Epoch 2/20
50000/50000 [==============================] - 13s 268us/step - loss: 1.6664 - acc: 0.3977 - val_loss: 1.5282 - val_acc: 0.4453
Epoch 3/20
 6528/50000 [==>...........................] - ETA: 10s - loss: 1.5956 - acc: 0.4225

50000/50000 [==============================] - 13s 263us/step - loss: 1.5558 - acc: 0.4373 - val_loss: 1.4989 - val_acc: 0.4568
Epoch 4/20
50000/50000 [==============================] - 13s 266us/step - loss: 1.4765 - acc: 0.4713 - val_loss: 1.3871 - val_acc: 0.5048
Epoch 5/20
27776/50000 [===============>..............] - ETA: 5s - loss: 1.4317 - acc: 0.4888

50000/50000 [==============================] - 13s 266us/step - loss: 1.4189 - acc: 0.4950 - val_loss: 1.3425 - val_acc: 0.5264
Epoch 6/20
50000/50000 [==============================] - 13s 263us/step - loss: 1.3671 - acc: 0.5144 - val_loss: 1.2760 - val_acc: 0.5510
Epoch 7/20
32640/50000 [==================>...........] - ETA: 4s - loss: 1.3296 - acc: 0.5301

50000/50000 [==============================] - 13s 265us/step - loss: 1.3220 - acc: 0.5319 - val_loss: 1.2261 - val_acc: 0.5717
Epoch 8/20
50000/50000 [==============================] - 13s 268us/step - loss: 1.2783 - acc: 0.5465 - val_loss: 1.1909 - val_acc: 0.5830
Epoch 9/20
33664/50000 [===================>..........] - ETA: 4s - loss: 1.2482 - acc: 0.5613

50000/50000 [==============================] - 13s 264us/step - loss: 1.2395 - acc: 0.5652 - val_loss: 1.1878 - val_acc: 0.5913
Epoch 10/20
50000/50000 [==============================] - 13s 265us/step - loss: 1.2054 - acc: 0.5777 - val_loss: 1.1929 - val_acc: 0.5845
Epoch 11/20
35200/50000 [====================>.........] - ETA: 3s - loss: 1.1720 - acc: 0.5922

50000/50000 [==============================] - 13s 263us/step - loss: 1.1724 - acc: 0.5918 - val_loss: 1.1489 - val_acc: 0.6026
Epoch 12/20
50000/50000 [==============================] - 13s 265us/step - loss: 1.1406 - acc: 0.6016 - val_loss: 1.0638 - val_acc: 0.6335
Epoch 13/20
34176/50000 [===================>..........] - ETA: 3s - loss: 1.1130 - acc: 0.6134

50000/50000 [==============================] - 13s 264us/step - loss: 1.1122 - acc: 0.6139 - val_loss: 1.0520 - val_acc: 0.6353
Epoch 14/20
50000/50000 [==============================] - 13s 263us/step - loss: 1.0833 - acc: 0.6239 - val_loss: 1.0155 - val_acc: 0.6486
Epoch 15/20
34944/50000 [===================>..........] - ETA: 3s - loss: 1.0609 - acc: 0.6330

50000/50000 [==============================] - 13s 263us/step - loss: 1.0567 - acc: 0.6342 - val_loss: 1.0044 - val_acc: 0.6550
Epoch 16/20
50000/50000 [==============================] - 13s 263us/step - loss: 1.0328 - acc: 0.6412 - val_loss: 0.9734 - val_acc: 0.6625
Epoch 17/20
34688/50000 [===================>..........] - ETA: 3s - loss: 1.0179 - acc: 0.6448

50000/50000 [==============================] - 13s 264us/step - loss: 1.0135 - acc: 0.6480 - val_loss: 0.9503 - val_acc: 0.6724
Epoch 18/20
50000/50000 [==============================] - 13s 267us/step - loss: 0.9913 - acc: 0.6551 - val_loss: 0.9368 - val_acc: 0.6757
Epoch 19/20
32640/50000 [==================>...........] - ETA: 4s - loss: 0.9740 - acc: 0.6645

50000/50000 [==============================] - 13s 265us/step - loss: 0.9721 - acc: 0.6655 - val_loss: 0.9616 - val_acc: 0.6625
Epoch 20/20
50000/50000 [==============================] - 13s 267us/step - loss: 0.9565 - acc: 0.6707 - val_loss: 0.9137 - val_acc: 0.6838

  - regularizer L2:
	Test loss:	 0.9137261812210083
	Test accuracy:	 0.6838
	Confusion Matrix:	
[[701  18  72  15  12  11  16   6 116  33]
 [ 17 807   9   5   5   6  19   3  50  79]
 [ 61   5 552  62  93  65 107  19  20  16]
 [ 12   7  90 455  71 179 131  14  21  20]
 [ 19   4  85  56 592  32 147  41  23   1]
 [ 15   1  84 170  44 577  69  27  10   3]
 [  5   4  37  36  13  13 881   2   6   3]
 [ 23   0  41  47  88  91  19 668   4  19]
 [ 55  29  13  13   5   3  12   2 842  26]
 [ 28  81  10  16   7   5  28  11  51 763]]


#### Base case with no dropouts

In [20]:
model = Sequential()

model.add(Conv2D(32, (3, 3), padding='same',
                 input_shape=x_train.shape[1:]))
model.add(Activation('relu'))
model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dense(num_classes))
model.add(Activation('softmax'))

opt = keras.optimizers.rmsprop(lr=0.0001, decay=1e-6)
model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])
model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_data=(x_test, y_test),shuffle=True)

print('\n  - Base case without dropouts:')
scores = model.evaluate(x_test, y_test, verbose=0)
print('\tTest loss:\t', scores[0])
print('\tTest accuracy:\t', scores[1])

Train on 50000 samples, validate on 10000 samples
Epoch 1/20
50000/50000 [==============================] - 14s 279us/step - loss: 1.8106 - acc: 0.3533 - val_loss: 1.5989 - val_acc: 0.4234
Epoch 2/20
50000/50000 [==============================] - 12s 243us/step - loss: 1.5339 - acc: 0.4515 - val_loss: 1.4927 - val_acc: 0.4688
Epoch 3/20
 9088/50000 [====>.........................] - ETA: 9s - loss: 1.4358 - acc: 0.4883

50000/50000 [==============================] - 12s 246us/step - loss: 1.4069 - acc: 0.5003 - val_loss: 1.3650 - val_acc: 0.5164
Epoch 4/20
50000/50000 [==============================] - 12s 241us/step - loss: 1.3248 - acc: 0.5341 - val_loss: 1.2682 - val_acc: 0.5512
Epoch 5/20
29824/50000 [================>.............] - ETA: 4s - loss: 1.2661 - acc: 0.5533

50000/50000 [==============================] - 12s 243us/step - loss: 1.2568 - acc: 0.5571 - val_loss: 1.2239 - val_acc: 0.5714
Epoch 6/20
50000/50000 [==============================] - 12s 245us/step - loss: 1.1978 - acc: 0.5804 - val_loss: 1.2441 - val_acc: 0.5698
Epoch 7/20
34944/50000 [===================>..........] - ETA: 3s - loss: 1.1506 - acc: 0.5989

50000/50000 [==============================] - 12s 244us/step - loss: 1.1435 - acc: 0.6024 - val_loss: 1.1634 - val_acc: 0.5944
Epoch 8/20
50000/50000 [==============================] - 12s 244us/step - loss: 1.0949 - acc: 0.6208 - val_loss: 1.1550 - val_acc: 0.6028
Epoch 9/20
36224/50000 [====================>.........] - ETA: 3s - loss: 1.0511 - acc: 0.6330

50000/50000 [==============================] - 12s 249us/step - loss: 1.0517 - acc: 0.6338 - val_loss: 1.0531 - val_acc: 0.6352
Epoch 10/20
50000/50000 [==============================] - 12s 243us/step - loss: 1.0114 - acc: 0.6493 - val_loss: 1.0672 - val_acc: 0.6308
Epoch 11/20
36224/50000 [====================>.........] - ETA: 3s - loss: 0.9810 - acc: 0.6607

50000/50000 [==============================] - 12s 245us/step - loss: 0.9736 - acc: 0.6634 - val_loss: 1.0193 - val_acc: 0.6484
Epoch 12/20
50000/50000 [==============================] - 12s 244us/step - loss: 0.9382 - acc: 0.6744 - val_loss: 1.0086 - val_acc: 0.6510
Epoch 13/20
36224/50000 [====================>.........] - ETA: 3s - loss: 0.9098 - acc: 0.6844

50000/50000 [==============================] - 12s 243us/step - loss: 0.9066 - acc: 0.6865 - val_loss: 1.0190 - val_acc: 0.6546
Epoch 14/20
50000/50000 [==============================] - 12s 246us/step - loss: 0.8724 - acc: 0.6989 - val_loss: 1.0658 - val_acc: 0.6264
Epoch 15/20
36224/50000 [====================>.........] - ETA: 3s - loss: 0.8486 - acc: 0.7089

50000/50000 [==============================] - 12s 244us/step - loss: 0.8440 - acc: 0.7103 - val_loss: 1.0072 - val_acc: 0.6578
Epoch 16/20
50000/50000 [==============================] - 12s 246us/step - loss: 0.8116 - acc: 0.7219 - val_loss: 0.9829 - val_acc: 0.6612
Epoch 17/20
36224/50000 [====================>.........] - ETA: 3s - loss: 0.7817 - acc: 0.7312

50000/50000 [==============================] - 12s 246us/step - loss: 0.7866 - acc: 0.7289 - val_loss: 0.9890 - val_acc: 0.6660
Epoch 18/20
50000/50000 [==============================] - 12s 243us/step - loss: 0.7573 - acc: 0.7408 - val_loss: 0.9508 - val_acc: 0.6797
Epoch 19/20
36224/50000 [====================>.........] - ETA: 3s - loss: 0.7273 - acc: 0.7512

50000/50000 [==============================] - 12s 245us/step - loss: 0.7298 - acc: 0.7493 - val_loss: 0.8967 - val_acc: 0.6927
Epoch 20/20
50000/50000 [==============================] - 12s 246us/step - loss: 0.7022 - acc: 0.7615 - val_loss: 0.9665 - val_acc: 0.6751

  - Base case without dropouts:
	Test loss:	 0.9664685956954956
	Test accuracy:	 0.6751


#### Model with Regularizer but no dropout

In [21]:
from keras import regularizers

weight_decay = 1e-4
model = Sequential()
model.add(Conv2D(32, (3, 3), padding='same', input_shape=x_train.shape[1:]))

model.add(Activation('relu'))
model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3), padding='same', kernel_regularizer=regularizers.l2(weight_decay)))
model.add(Activation('relu'))
model.add(Conv2D(64, (3, 3), kernel_regularizer=regularizers.l2(weight_decay)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dense(num_classes))
model.add(Activation('softmax'))

opt = keras.optimizers.rmsprop(lr=0.0001, decay=1e-6)
model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])
model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_data=(x_test, y_test), shuffle=True)

print('\n  - regularizer L2 without dropout:')
scores = model.evaluate(x_test, y_test, verbose=0)
print('\tTest loss:\t', scores[0])
print('\tTest accuracy:\t', scores[1])

Train on 50000 samples, validate on 10000 samples
Epoch 1/20
50000/50000 [==============================] - 14s 282us/step - loss: 1.8228 - acc: 0.3531 - val_loss: 1.6782 - val_acc: 0.4014
Epoch 2/20
50000/50000 [==============================] - 12s 248us/step - loss: 1.5387 - acc: 0.4533 - val_loss: 1.4508 - val_acc: 0.4773
Epoch 3/20
 9344/50000 [====>.........................] - ETA: 9s - loss: 1.4520 - acc: 0.4853

50000/50000 [==============================] - 12s 248us/step - loss: 1.4228 - acc: 0.4977 - val_loss: 1.4084 - val_acc: 0.5025
Epoch 4/20
50000/50000 [==============================] - 12s 245us/step - loss: 1.3354 - acc: 0.5303 - val_loss: 1.3079 - val_acc: 0.5421
Epoch 5/20
30336/50000 [=================>............] - ETA: 4s - loss: 1.2772 - acc: 0.5568

50000/50000 [==============================] - 12s 248us/step - loss: 1.2687 - acc: 0.5571 - val_loss: 1.3178 - val_acc: 0.5358
Epoch 6/20
50000/50000 [==============================] - 12s 246us/step - loss: 1.2059 - acc: 0.5810 - val_loss: 1.2183 - val_acc: 0.5664
Epoch 7/20
35200/50000 [====================>.........] - ETA: 3s - loss: 1.1604 - acc: 0.6018

50000/50000 [==============================] - 12s 247us/step - loss: 1.1533 - acc: 0.6030 - val_loss: 1.1433 - val_acc: 0.5973
Epoch 8/20
50000/50000 [==============================] - 12s 248us/step - loss: 1.1051 - acc: 0.6186 - val_loss: 1.1605 - val_acc: 0.5949
Epoch 9/20
36224/50000 [====================>.........] - ETA: 3s - loss: 1.0653 - acc: 0.6332

50000/50000 [==============================] - 12s 248us/step - loss: 1.0642 - acc: 0.6340 - val_loss: 1.1030 - val_acc: 0.6092
Epoch 10/20
50000/50000 [==============================] - 12s 244us/step - loss: 1.0239 - acc: 0.6501 - val_loss: 1.1024 - val_acc: 0.6147
Epoch 11/20
36224/50000 [====================>.........] - ETA: 3s - loss: 0.9919 - acc: 0.6601

50000/50000 [==============================] - 12s 246us/step - loss: 0.9905 - acc: 0.6613 - val_loss: 1.0822 - val_acc: 0.6170
Epoch 12/20
50000/50000 [==============================] - 12s 245us/step - loss: 0.9549 - acc: 0.6737 - val_loss: 1.0225 - val_acc: 0.6513
Epoch 13/20
36224/50000 [====================>.........] - ETA: 3s - loss: 0.9269 - acc: 0.6863

50000/50000 [==============================] - 12s 245us/step - loss: 0.9231 - acc: 0.6871 - val_loss: 1.0047 - val_acc: 0.6551
Epoch 14/20
50000/50000 [==============================] - 12s 245us/step - loss: 0.8944 - acc: 0.6962 - val_loss: 0.9613 - val_acc: 0.6720
Epoch 15/20
35968/50000 [====================>.........] - ETA: 3s - loss: 0.8581 - acc: 0.7100

50000/50000 [==============================] - 12s 245us/step - loss: 0.8626 - acc: 0.7076 - val_loss: 1.0454 - val_acc: 0.6464
Epoch 16/20
50000/50000 [==============================] - 12s 245us/step - loss: 0.8356 - acc: 0.7176 - val_loss: 1.0107 - val_acc: 0.6577
Epoch 17/20
35968/50000 [====================>.........] - ETA: 3s - loss: 0.8022 - acc: 0.7300

50000/50000 [==============================] - 13s 250us/step - loss: 0.8049 - acc: 0.7291 - val_loss: 0.9677 - val_acc: 0.6690
Epoch 18/20
50000/50000 [==============================] - 13s 252us/step - loss: 0.7798 - acc: 0.7405 - val_loss: 1.1470 - val_acc: 0.6236
Epoch 19/20
35968/50000 [====================>.........] - ETA: 3s - loss: 0.7520 - acc: 0.7477

50000/50000 [==============================] - 12s 250us/step - loss: 0.7513 - acc: 0.7472 - val_loss: 0.9316 - val_acc: 0.6834
Epoch 20/20
50000/50000 [==============================] - 13s 252us/step - loss: 0.7244 - acc: 0.7562 - val_loss: 0.9376 - val_acc: 0.6883

  - regularizer L2 without dropout:
	Test loss:	 0.9376100969314575
	Test accuracy:	 0.6883
