# CIFAR10 with CNN
code from https://github.com/fchollet/keras/blob/master/examples/mnist_cnn.py


This notebook trains a simple convolutional neural network on the CIFAR10 small images dataset. 



In [0]:
# import libraries
from __future__ import print_function
from __future__ import print_function
import keras
from keras.datasets import cifar10
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D

#for confusion matrix
import numpy as np
import sklearn
from sklearn.metrics import confusion_matrix


Prepare data

In [10]:
# define constants
batch_size = 128
num_classes = 10
epochs = 20


# The data, shuffled and split between train and test sets:
(x_train, y_train), (x_test, y_test) = cifar10.load_data()
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# Convert class vectors to binary class matrices.
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

# Cast features into correct data type then scale features
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

x_train shape: (50000, 32, 32, 3)
50000 train samples
10000 test samples


Define model

In [0]:
model = Sequential()

model.add(Conv2D(32, (3, 3), padding='same',
                 input_shape=x_train.shape[1:]))
model.add(Activation('relu'))
model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(64, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes))
model.add(Activation('softmax'))


Show model structure

In [12]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_5 (Conv2D)            (None, 32, 32, 32)        896       
_________________________________________________________________
activation_7 (Activation)    (None, 32, 32, 32)        0         
_________________________________________________________________
conv2d_6 (Conv2D)            (None, 30, 30, 32)        9248      
_________________________________________________________________
activation_8 (Activation)    (None, 30, 30, 32)        0         
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 15, 15, 32)        0         
_________________________________________________________________
dropout_4 (Dropout)          (None, 15, 15, 32)        0         
_________________________________________________________________
conv2d_7 (Conv2D)            (None, 15, 15, 64)        18496     
__________

Compile model and fit


In [13]:
# initiate RMSprop optimizer
opt = keras.optimizers.rmsprop(lr=0.0001, decay=1e-6)

# Let's train the model using RMSprop
model.compile(loss='categorical_crossentropy',
              optimizer=opt,
                metrics=['accuracy'])


model.fit(x_train, y_train,
            batch_size=batch_size,
            epochs=epochs,
            validation_data=(x_test, y_test),
            shuffle=True)




Train on 50000 samples, validate on 10000 samples
Epoch 1/20
50000/50000 [==============================] - 14s 272us/step - loss: 1.9766 - acc: 0.2752 - val_loss: 1.7337 - val_acc: 0.3869
Epoch 2/20
50000/50000 [==============================] - 13s 262us/step - loss: 1.7088 - acc: 0.3814 - val_loss: 1.5992 - val_acc: 0.4358
Epoch 3/20
 9088/50000 [====>.........................] - ETA: 10s - loss: 1.6215 - acc: 0.4133

50000/50000 [==============================] - 13s 263us/step - loss: 1.5838 - acc: 0.4274 - val_loss: 1.5235 - val_acc: 0.4569
Epoch 4/20
50000/50000 [==============================] - 13s 262us/step - loss: 1.4976 - acc: 0.4599 - val_loss: 1.4065 - val_acc: 0.4958
Epoch 5/20
29824/50000 [================>.............] - ETA: 5s - loss: 1.4437 - acc: 0.4835

50000/50000 [==============================] - 13s 265us/step - loss: 1.4306 - acc: 0.4862 - val_loss: 1.3208 - val_acc: 0.5278
Epoch 6/20
50000/50000 [==============================] - 13s 261us/step - loss: 1.3757 - acc: 0.5061 - val_loss: 1.2874 - val_acc: 0.5418
Epoch 7/20
34688/50000 [===================>..........] - ETA: 3s - loss: 1.3266 - acc: 0.5281

50000/50000 [==============================] - 13s 262us/step - loss: 1.3254 - acc: 0.5280 - val_loss: 1.2291 - val_acc: 0.5637
Epoch 8/20
50000/50000 [==============================] - 13s 259us/step - loss: 1.2850 - acc: 0.5409 - val_loss: 1.2176 - val_acc: 0.5711
Epoch 9/20
35968/50000 [====================>.........] - ETA: 3s - loss: 1.2539 - acc: 0.5552

50000/50000 [==============================] - 13s 257us/step - loss: 1.2488 - acc: 0.5563 - val_loss: 1.1548 - val_acc: 0.5942
Epoch 10/20
50000/50000 [==============================] - 13s 256us/step - loss: 1.2122 - acc: 0.5714 - val_loss: 1.1243 - val_acc: 0.6030
Epoch 11/20
35200/50000 [====================>.........] - ETA: 3s - loss: 1.1787 - acc: 0.5845

50000/50000 [==============================] - 13s 257us/step - loss: 1.1793 - acc: 0.5859 - val_loss: 1.1110 - val_acc: 0.6127
Epoch 12/20
50000/50000 [==============================] - 13s 260us/step - loss: 1.1507 - acc: 0.5943 - val_loss: 1.0982 - val_acc: 0.6134
Epoch 13/20
35456/50000 [====================>.........] - ETA: 3s - loss: 1.1236 - acc: 0.6031

50000/50000 [==============================] - 13s 260us/step - loss: 1.1214 - acc: 0.6028 - val_loss: 1.0515 - val_acc: 0.6301
Epoch 14/20
50000/50000 [==============================] - 13s 261us/step - loss: 1.0915 - acc: 0.6158 - val_loss: 1.0232 - val_acc: 0.6404
Epoch 15/20
34688/50000 [===================>..........] - ETA: 3s - loss: 1.0706 - acc: 0.6253

50000/50000 [==============================] - 13s 265us/step - loss: 1.0662 - acc: 0.6280 - val_loss: 1.0502 - val_acc: 0.6284
Epoch 16/20
50000/50000 [==============================] - 13s 265us/step - loss: 1.0409 - acc: 0.6355 - val_loss: 0.9791 - val_acc: 0.6602
Epoch 17/20
34176/50000 [===================>..........] - ETA: 3s - loss: 1.0215 - acc: 0.6434

50000/50000 [==============================] - 13s 265us/step - loss: 1.0194 - acc: 0.6435 - val_loss: 1.0054 - val_acc: 0.6525
Epoch 18/20
50000/50000 [==============================] - 13s 267us/step - loss: 0.9992 - acc: 0.6503 - val_loss: 0.9778 - val_acc: 0.6576
Epoch 19/20
33920/50000 [===================>..........] - ETA: 4s - loss: 0.9752 - acc: 0.6591

50000/50000 [==============================] - 13s 266us/step - loss: 0.9750 - acc: 0.6574 - val_loss: 0.9303 - val_acc: 0.6755
Epoch 20/20
50000/50000 [==============================] - 13s 264us/step - loss: 0.9599 - acc: 0.6645 - val_loss: 0.9348 - val_acc: 0.6758


In [0]:
# Save the original model
model.save('cifra10_base.h5')

In [15]:
# Print base model loss and accuracy
print('\n  - Base case:')
model = keras.models.load_model("cifra10_base.h5")
scores = model.evaluate(x_test, y_test, verbose=0)
print('\tTest loss:\t', scores[0])
print('\tTest accuracy:\t', scores[1])
Y_pred = model.predict(x_test, verbose=2)
cm = confusion_matrix(np.argmax(y_test,axis=1),np.argmax(Y_pred, axis=1))
print('\tConfusion Matrix:\t')
print(cm)


  - Base case:
	Test loss:	 0.9348436509132385
	Test accuracy:	 0.6758
	Confusion Matrix:	
[[768  52  26  13   5   3   9   6  68  50]
 [ 13 911   2   2   0   0   6   1  12  53]
 [102  30 502  69  92  61  66  41  19  18]
 [ 38  41  70 457  54 141  73  56  31  39]
 [ 43  18  94  61 526  28  78 126  17   9]
 [ 29  17  63 172  32 550  28  77  17  15]
 [ 13  22  43  66  32  14 770   9   8  23]
 [ 33  15  31  31  40  49   7 751   4  39]
 [ 71  78   9   7   1   4   3   3 791  33]
 [ 30 179   3   8   3   5  11  11  18 732]]


### 1) Augment the data by adding noise. Discuss results.

In [16]:
# Save models with gaussian noise with different Standard Deviation
for e in [0.5,0.1,0.05,0.02,0.01]:
    model = keras.models.load_model("cifra10_base.h5")
    model.add(keras.layers.GaussianNoise(e))
    model.compile(loss='categorical_crossentropy',
                  optimizer=opt,
                    metrics=['accuracy'])
    model.fit(x_train, y_train,
                batch_size=batch_size,
                epochs=epochs,
                validation_data=(x_test, y_test),
                shuffle=True)
    model.save('cifra10_n'+str(e)+'.h5')

Train on 50000 samples, validate on 10000 samples
Epoch 1/20
50000/50000 [==============================] - 14s 287us/step - loss: 5.6383 - acc: 0.3516 - val_loss: 1.0401 - val_acc: 0.6606
Epoch 2/20
50000/50000 [==============================] - 14s 270us/step - loss: 5.7322 - acc: 0.3581 - val_loss: 1.1184 - val_acc: 0.6453
Epoch 3/20
 6272/50000 [==>...........................] - ETA: 11s - loss: 5.6725 - acc: 0.3710

50000/50000 [==============================] - 14s 271us/step - loss: 5.7587 - acc: 0.3607 - val_loss: 2.0146 - val_acc: 0.5251
Epoch 4/20
50000/50000 [==============================] - 14s 271us/step - loss: 5.7041 - acc: 0.3687 - val_loss: 1.8109 - val_acc: 0.5755
Epoch 5/20
25216/50000 [==============>...............] - ETA: 6s - loss: 5.8295 - acc: 0.3488

50000/50000 [==============================] - 13s 270us/step - loss: 5.7508 - acc: 0.3595 - val_loss: 1.6099 - val_acc: 0.5887
Epoch 6/20
50000/50000 [==============================] - 13s 269us/step - loss: 5.8275 - acc: 0.3555 - val_loss: 1.4313 - val_acc: 0.6172
Epoch 7/20
30080/50000 [=================>............] - ETA: 5s - loss: 5.7712 - acc: 0.3425

50000/50000 [==============================] - 13s 267us/step - loss: 5.7989 - acc: 0.3488 - val_loss: 1.7460 - val_acc: 0.5820
Epoch 8/20
50000/50000 [==============================] - 14s 271us/step - loss: 5.7162 - acc: 0.3569 - val_loss: 1.3900 - val_acc: 0.6248
Epoch 9/20
30336/50000 [=================>............] - ETA: 5s - loss: 5.7664 - acc: 0.3622

50000/50000 [==============================] - 13s 269us/step - loss: 5.7074 - acc: 0.3669 - val_loss: 1.3688 - val_acc: 0.6276
Epoch 10/20
50000/50000 [==============================] - 13s 266us/step - loss: 5.7382 - acc: 0.3608 - val_loss: 1.4451 - val_acc: 0.6167
Epoch 11/20
30848/50000 [=================>............] - ETA: 4s - loss: 5.8428 - acc: 0.3684

50000/50000 [==============================] - 13s 266us/step - loss: 5.7812 - acc: 0.3742 - val_loss: 1.9533 - val_acc: 0.5522
Epoch 12/20
50000/50000 [==============================] - 13s 267us/step - loss: 5.6932 - acc: 0.3710 - val_loss: 1.4649 - val_acc: 0.6274
Epoch 13/20
32128/50000 [==================>...........] - ETA: 4s - loss: 5.7336 - acc: 0.3813

50000/50000 [==============================] - 13s 267us/step - loss: 5.7335 - acc: 0.3792 - val_loss: 2.0371 - val_acc: 0.5368
Epoch 14/20
50000/50000 [==============================] - 13s 269us/step - loss: 5.7280 - acc: 0.3835 - val_loss: 1.5463 - val_acc: 0.6198
Epoch 15/20
32896/50000 [==================>...........] - ETA: 4s - loss: 5.7175 - acc: 0.3781

50000/50000 [==============================] - 13s 265us/step - loss: 5.7049 - acc: 0.3767 - val_loss: 1.7299 - val_acc: 0.5973
Epoch 16/20
50000/50000 [==============================] - 14s 270us/step - loss: 5.7389 - acc: 0.3855 - val_loss: 1.4248 - val_acc: 0.6330
Epoch 17/20
30592/50000 [=================>............] - ETA: 4s - loss: 5.8286 - acc: 0.3652

50000/50000 [==============================] - 13s 266us/step - loss: 5.7500 - acc: 0.3740 - val_loss: 1.4435 - val_acc: 0.6296
Epoch 18/20
50000/50000 [==============================] - 13s 269us/step - loss: 5.6674 - acc: 0.3831 - val_loss: 1.4782 - val_acc: 0.6284
Epoch 19/20
31872/50000 [==================>...........] - ETA: 4s - loss: 5.6772 - acc: 0.3801

50000/50000 [==============================] - 13s 267us/step - loss: 5.6830 - acc: 0.3747 - val_loss: 1.4231 - val_acc: 0.6327
Epoch 20/20
50000/50000 [==============================] - 13s 268us/step - loss: 5.7050 - acc: 0.3695 - val_loss: 1.4783 - val_acc: 0.6273
Train on 50000 samples, validate on 10000 samples
Epoch 1/20
27520/50000 [===============>..............] - ETA: 6s - loss: 1.5461 - acc: 0.6448

50000/50000 [==============================] - 14s 289us/step - loss: 1.5480 - acc: 0.6454 - val_loss: 0.9283 - val_acc: 0.6726
Epoch 2/20
50000/50000 [==============================] - 13s 266us/step - loss: 1.5137 - acc: 0.6451 - val_loss: 1.1436 - val_acc: 0.5936
Epoch 3/20
31104/50000 [=================>............] - ETA: 4s - loss: 1.5590 - acc: 0.6441

50000/50000 [==============================] - 13s 265us/step - loss: 1.5562 - acc: 0.6452 - val_loss: 0.9652 - val_acc: 0.6582
Epoch 4/20
50000/50000 [==============================] - 13s 265us/step - loss: 1.5287 - acc: 0.6468 - val_loss: 0.9424 - val_acc: 0.6728
Epoch 5/20
32640/50000 [==================>...........] - ETA: 4s - loss: 1.5162 - acc: 0.6490

50000/50000 [==============================] - 13s 267us/step - loss: 1.5420 - acc: 0.6463 - val_loss: 0.9530 - val_acc: 0.6713
Epoch 6/20
50000/50000 [==============================] - 13s 265us/step - loss: 1.5272 - acc: 0.6492 - val_loss: 0.9848 - val_acc: 0.6534
Epoch 7/20
33408/50000 [===================>..........] - ETA: 4s - loss: 1.4888 - acc: 0.6560

50000/50000 [==============================] - 13s 265us/step - loss: 1.5125 - acc: 0.6573 - val_loss: 0.9178 - val_acc: 0.6838
Epoch 8/20
50000/50000 [==============================] - 13s 267us/step - loss: 1.4858 - acc: 0.6639 - val_loss: 0.9029 - val_acc: 0.6818
Epoch 9/20
33920/50000 [===================>..........] - ETA: 4s - loss: 1.4838 - acc: 0.6607

50000/50000 [==============================] - 13s 266us/step - loss: 1.4914 - acc: 0.6594 - val_loss: 1.0473 - val_acc: 0.6365
Epoch 10/20
50000/50000 [==============================] - 13s 269us/step - loss: 1.5034 - acc: 0.6554 - val_loss: 0.9055 - val_acc: 0.6859
Epoch 11/20
31872/50000 [==================>...........] - ETA: 4s - loss: 1.4701 - acc: 0.6601

50000/50000 [==============================] - 13s 267us/step - loss: 1.4709 - acc: 0.6616 - val_loss: 0.9253 - val_acc: 0.6802
Epoch 12/20
50000/50000 [==============================] - 13s 267us/step - loss: 1.5285 - acc: 0.6432 - val_loss: 0.9100 - val_acc: 0.6868
Epoch 13/20
32384/50000 [==================>...........] - ETA: 4s - loss: 1.5323 - acc: 0.6501

50000/50000 [==============================] - 13s 267us/step - loss: 1.4908 - acc: 0.6551 - val_loss: 0.8894 - val_acc: 0.6882
Epoch 14/20
50000/50000 [==============================] - 13s 267us/step - loss: 1.4621 - acc: 0.6638 - val_loss: 0.8739 - val_acc: 0.7001
Epoch 15/20
33408/50000 [===================>..........] - ETA: 4s - loss: 1.4550 - acc: 0.6661

50000/50000 [==============================] - 13s 267us/step - loss: 1.4386 - acc: 0.6663 - val_loss: 0.8984 - val_acc: 0.6971
Epoch 16/20
50000/50000 [==============================] - 13s 265us/step - loss: 1.4609 - acc: 0.6678 - val_loss: 0.8803 - val_acc: 0.7008
Epoch 17/20
34176/50000 [===================>..........] - ETA: 3s - loss: 1.4249 - acc: 0.6730

50000/50000 [==============================] - 13s 264us/step - loss: 1.4213 - acc: 0.6743 - val_loss: 0.8615 - val_acc: 0.7055
Epoch 18/20
50000/50000 [==============================] - 13s 262us/step - loss: 1.4219 - acc: 0.6781 - val_loss: 0.9109 - val_acc: 0.6912
Epoch 19/20
33664/50000 [===================>..........] - ETA: 4s - loss: 1.4199 - acc: 0.6778

50000/50000 [==============================] - 13s 266us/step - loss: 1.4034 - acc: 0.6765 - val_loss: 0.8579 - val_acc: 0.7035
Epoch 20/20
50000/50000 [==============================] - 13s 265us/step - loss: 1.4367 - acc: 0.6757 - val_loss: 0.8635 - val_acc: 0.7043
Train on 50000 samples, validate on 10000 samples
Epoch 1/20
29056/50000 [================>.............] - ETA: 6s - loss: 1.2247 - acc: 0.6619

50000/50000 [==============================] - 15s 291us/step - loss: 1.2177 - acc: 0.6615 - val_loss: 0.9130 - val_acc: 0.6821
Epoch 2/20
50000/50000 [==============================] - 13s 268us/step - loss: 1.2280 - acc: 0.6617 - val_loss: 0.8980 - val_acc: 0.6932
Epoch 3/20
30336/50000 [=================>............] - ETA: 5s - loss: 1.2315 - acc: 0.6618

50000/50000 [==============================] - 13s 270us/step - loss: 1.2338 - acc: 0.6625 - val_loss: 0.8904 - val_acc: 0.6904
Epoch 4/20
50000/50000 [==============================] - 13s 268us/step - loss: 1.1939 - acc: 0.6665 - val_loss: 0.8942 - val_acc: 0.6872
Epoch 5/20
32640/50000 [==================>...........] - ETA: 4s - loss: 1.1711 - acc: 0.6729

50000/50000 [==============================] - 13s 268us/step - loss: 1.1821 - acc: 0.6698 - val_loss: 0.9206 - val_acc: 0.6747
Epoch 6/20
50000/50000 [==============================] - 13s 268us/step - loss: 1.1786 - acc: 0.6739 - val_loss: 0.9003 - val_acc: 0.6860
Epoch 7/20
33664/50000 [===================>..........] - ETA: 4s - loss: 1.1752 - acc: 0.6753

50000/50000 [==============================] - 13s 267us/step - loss: 1.1760 - acc: 0.6761 - val_loss: 0.8891 - val_acc: 0.6972
Epoch 8/20
50000/50000 [==============================] - 13s 268us/step - loss: 1.1809 - acc: 0.6746 - val_loss: 0.8815 - val_acc: 0.6980
Epoch 9/20
32896/50000 [==================>...........] - ETA: 4s - loss: 1.1530 - acc: 0.6804

50000/50000 [==============================] - 13s 266us/step - loss: 1.1503 - acc: 0.6811 - val_loss: 0.8635 - val_acc: 0.7010
Epoch 10/20
50000/50000 [==============================] - 13s 270us/step - loss: 1.1503 - acc: 0.6837 - val_loss: 0.8613 - val_acc: 0.7032
Epoch 11/20
33152/50000 [==================>...........] - ETA: 4s - loss: 1.1696 - acc: 0.6824

50000/50000 [==============================] - 13s 267us/step - loss: 1.1572 - acc: 0.6847 - val_loss: 0.8573 - val_acc: 0.7039
Epoch 12/20
50000/50000 [==============================] - 13s 269us/step - loss: 1.1442 - acc: 0.6902 - val_loss: 0.8888 - val_acc: 0.6901
Epoch 13/20
34176/50000 [===================>..........] - ETA: 3s - loss: 1.1219 - acc: 0.6912

50000/50000 [==============================] - 13s 268us/step - loss: 1.1263 - acc: 0.6913 - val_loss: 0.8524 - val_acc: 0.7061
Epoch 14/20
50000/50000 [==============================] - 13s 270us/step - loss: 1.1321 - acc: 0.6903 - val_loss: 0.8525 - val_acc: 0.7052
Epoch 15/20
32640/50000 [==================>...........] - ETA: 4s - loss: 1.1275 - acc: 0.6940

50000/50000 [==============================] - 13s 267us/step - loss: 1.1134 - acc: 0.6941 - val_loss: 0.8614 - val_acc: 0.7057
Epoch 16/20
50000/50000 [==============================] - 13s 269us/step - loss: 1.1276 - acc: 0.6914 - val_loss: 0.8501 - val_acc: 0.7073
Epoch 17/20
31360/50000 [=================>............] - ETA: 4s - loss: 1.1192 - acc: 0.6941

50000/50000 [==============================] - 13s 269us/step - loss: 1.1167 - acc: 0.6952 - val_loss: 0.8408 - val_acc: 0.7123
Epoch 18/20
50000/50000 [==============================] - 13s 268us/step - loss: 1.0940 - acc: 0.6986 - val_loss: 0.8231 - val_acc: 0.7144
Epoch 19/20
31104/50000 [=================>............] - ETA: 4s - loss: 1.0855 - acc: 0.7021

50000/50000 [==============================] - 13s 269us/step - loss: 1.0902 - acc: 0.6993 - val_loss: 0.8189 - val_acc: 0.7178
Epoch 20/20
50000/50000 [==============================] - 13s 269us/step - loss: 1.0739 - acc: 0.7031 - val_loss: 0.8434 - val_acc: 0.7109
Train on 50000 samples, validate on 10000 samples
Epoch 1/20
28288/50000 [===============>..............] - ETA: 6s - loss: 1.0484 - acc: 0.6668

50000/50000 [==============================] - 15s 302us/step - loss: 1.0465 - acc: 0.6689 - val_loss: 0.9199 - val_acc: 0.6789
Epoch 2/20
50000/50000 [==============================] - 13s 270us/step - loss: 1.0441 - acc: 0.6732 - val_loss: 0.8859 - val_acc: 0.6909
Epoch 3/20
31104/50000 [=================>............] - ETA: 4s - loss: 1.0230 - acc: 0.6765

50000/50000 [==============================] - 13s 270us/step - loss: 1.0294 - acc: 0.6762 - val_loss: 0.9449 - val_acc: 0.6685
Epoch 4/20
50000/50000 [==============================] - 13s 269us/step - loss: 1.0279 - acc: 0.6766 - val_loss: 0.8678 - val_acc: 0.6972
Epoch 5/20
31872/50000 [==================>...........] - ETA: 4s - loss: 0.9978 - acc: 0.6868

50000/50000 [==============================] - 13s 270us/step - loss: 1.0036 - acc: 0.6846 - val_loss: 0.8722 - val_acc: 0.7029
Epoch 6/20
50000/50000 [==============================] - 13s 270us/step - loss: 1.0021 - acc: 0.6856 - val_loss: 0.8539 - val_acc: 0.7019
Epoch 7/20
32896/50000 [==================>...........] - ETA: 4s - loss: 0.9846 - acc: 0.6881

50000/50000 [==============================] - 14s 270us/step - loss: 0.9829 - acc: 0.6875 - val_loss: 0.8858 - val_acc: 0.6922
Epoch 8/20
50000/50000 [==============================] - 13s 269us/step - loss: 0.9716 - acc: 0.6932 - val_loss: 0.8540 - val_acc: 0.7054
Epoch 9/20
30848/50000 [=================>............] - ETA: 4s - loss: 0.9699 - acc: 0.6937

50000/50000 [==============================] - 14s 271us/step - loss: 0.9611 - acc: 0.6960 - val_loss: 0.9252 - val_acc: 0.6715
Epoch 10/20
50000/50000 [==============================] - 13s 268us/step - loss: 0.9456 - acc: 0.7006 - val_loss: 0.8380 - val_acc: 0.7141
Epoch 11/20
30848/50000 [=================>............] - ETA: 4s - loss: 0.9269 - acc: 0.7081

50000/50000 [==============================] - 14s 271us/step - loss: 0.9356 - acc: 0.7050 - val_loss: 0.8096 - val_acc: 0.7200
Epoch 12/20
50000/50000 [==============================] - 13s 269us/step - loss: 0.9412 - acc: 0.7057 - val_loss: 0.8259 - val_acc: 0.7177
Epoch 13/20
31616/50000 [=================>............] - ETA: 4s - loss: 0.9281 - acc: 0.7038

50000/50000 [==============================] - 14s 271us/step - loss: 0.9279 - acc: 0.7061 - val_loss: 0.7981 - val_acc: 0.7230
Epoch 14/20
50000/50000 [==============================] - 14s 271us/step - loss: 0.9165 - acc: 0.7122 - val_loss: 0.8186 - val_acc: 0.7178
Epoch 15/20
30336/50000 [=================>............] - ETA: 5s - loss: 0.9137 - acc: 0.7141

50000/50000 [==============================] - 14s 271us/step - loss: 0.9142 - acc: 0.7156 - val_loss: 0.7904 - val_acc: 0.7304
Epoch 16/20
50000/50000 [==============================] - 14s 271us/step - loss: 0.8983 - acc: 0.7215 - val_loss: 0.7975 - val_acc: 0.7263
Epoch 17/20
30592/50000 [=================>............] - ETA: 4s - loss: 0.8922 - acc: 0.7212

50000/50000 [==============================] - 13s 269us/step - loss: 0.8971 - acc: 0.7208 - val_loss: 0.8827 - val_acc: 0.7031
Epoch 18/20
50000/50000 [==============================] - 14s 272us/step - loss: 0.8931 - acc: 0.7271 - val_loss: 0.7853 - val_acc: 0.7354
Epoch 19/20
30336/50000 [=================>............] - ETA: 5s - loss: 0.8523 - acc: 0.7269

50000/50000 [==============================] - 14s 274us/step - loss: 0.8657 - acc: 0.7264 - val_loss: 0.9021 - val_acc: 0.6983
Epoch 20/20
50000/50000 [==============================] - 14s 272us/step - loss: 0.8700 - acc: 0.7293 - val_loss: 0.8100 - val_acc: 0.7270
Train on 50000 samples, validate on 10000 samples
Epoch 1/20
27776/50000 [===============>..............] - ETA: 6s - loss: 0.9950 - acc: 0.6723

50000/50000 [==============================] - 15s 299us/step - loss: 0.9966 - acc: 0.6692 - val_loss: 0.9223 - val_acc: 0.6798
Epoch 2/20
50000/50000 [==============================] - 14s 270us/step - loss: 0.9783 - acc: 0.6761 - val_loss: 0.8901 - val_acc: 0.6927
Epoch 3/20
28032/50000 [===============>..............] - ETA: 5s - loss: 0.9604 - acc: 0.6836

50000/50000 [==============================] - 14s 273us/step - loss: 0.9607 - acc: 0.6826 - val_loss: 0.8818 - val_acc: 0.6909
Epoch 4/20
50000/50000 [==============================] - 14s 273us/step - loss: 0.9519 - acc: 0.6821 - val_loss: 0.8703 - val_acc: 0.6985
Epoch 5/20
31104/50000 [=================>............] - ETA: 4s - loss: 0.9320 - acc: 0.6888

50000/50000 [==============================] - 14s 272us/step - loss: 0.9363 - acc: 0.6886 - val_loss: 0.9113 - val_acc: 0.6847
Epoch 6/20
50000/50000 [==============================] - 14s 271us/step - loss: 0.9278 - acc: 0.6931 - val_loss: 0.8359 - val_acc: 0.7129
Epoch 7/20
29184/50000 [================>.............] - ETA: 5s - loss: 0.9226 - acc: 0.6952

50000/50000 [==============================] - 14s 274us/step - loss: 0.9142 - acc: 0.6978 - val_loss: 0.8259 - val_acc: 0.7147
Epoch 8/20
50000/50000 [==============================] - 14s 275us/step - loss: 0.8948 - acc: 0.7007 - val_loss: 0.8455 - val_acc: 0.7048
Epoch 9/20
28544/50000 [================>.............] - ETA: 5s - loss: 0.8910 - acc: 0.7061

50000/50000 [==============================] - 14s 276us/step - loss: 0.8985 - acc: 0.7053 - val_loss: 0.8358 - val_acc: 0.7160
Epoch 10/20
50000/50000 [==============================] - 14s 274us/step - loss: 0.8842 - acc: 0.7093 - val_loss: 0.8027 - val_acc: 0.7247
Epoch 11/20
29568/50000 [================>.............] - ETA: 5s - loss: 0.8518 - acc: 0.7147

50000/50000 [==============================] - 14s 277us/step - loss: 0.8608 - acc: 0.7139 - val_loss: 0.7991 - val_acc: 0.7238
Epoch 12/20
50000/50000 [==============================] - 14s 277us/step - loss: 0.8593 - acc: 0.7163 - val_loss: 0.7970 - val_acc: 0.7238
Epoch 13/20
29440/50000 [================>.............] - ETA: 5s - loss: 0.8674 - acc: 0.7158

50000/50000 [==============================] - 14s 278us/step - loss: 0.8618 - acc: 0.7187 - val_loss: 0.7799 - val_acc: 0.7335
Epoch 14/20
50000/50000 [==============================] - 14s 276us/step - loss: 0.8346 - acc: 0.7216 - val_loss: 0.7820 - val_acc: 0.7310
Epoch 15/20
31232/50000 [=================>............] - ETA: 4s - loss: 0.8294 - acc: 0.7271

50000/50000 [==============================] - 14s 281us/step - loss: 0.8272 - acc: 0.7277 - val_loss: 0.7726 - val_acc: 0.7324
Epoch 16/20
50000/50000 [==============================] - 14s 279us/step - loss: 0.8091 - acc: 0.7313 - val_loss: 0.7724 - val_acc: 0.7341
Epoch 17/20
30592/50000 [=================>............] - ETA: 5s - loss: 0.8111 - acc: 0.7340

50000/50000 [==============================] - 14s 277us/step - loss: 0.8151 - acc: 0.7335 - val_loss: 0.7683 - val_acc: 0.7365
Epoch 18/20
50000/50000 [==============================] - 14s 271us/step - loss: 0.8033 - acc: 0.7369 - val_loss: 0.7512 - val_acc: 0.7404
Epoch 19/20
28032/50000 [===============>..............] - ETA: 5s - loss: 0.7926 - acc: 0.7403

50000/50000 [==============================] - 14s 271us/step - loss: 0.7941 - acc: 0.7381 - val_loss: 0.7466 - val_acc: 0.7455
Epoch 20/20
50000/50000 [==============================] - 14s 270us/step - loss: 0.7820 - acc: 0.7440 - val_loss: 0.7355 - val_acc: 0.7488


In [17]:
# Load models and print results
for e in [0.5,0.1,0.05,0.02,0.01]:
    model = keras.models.load_model('cifra10_n'+str(e)+'.h5')
    print('\n  - Gaussian Noise with '+str(e)+' stdev:')
    scores = model.evaluate(x_test, y_test, verbose=0)
    print('\tTest loss:\t', scores[0])
    print('\tTest accuracy:\t', scores[1])
    
# Load and print of the best loss and accuracy obtained
model = keras.models.load_model("cifra10_n0.02.h5")
print('\n\nBest results:')
print('  - Gaussian Noise with 0.02 stdev:')
scores = model.evaluate(x_test, y_test, verbose=0)
print('\tTest loss:\t', scores[0])
print('\tTest accuracy:\t', scores[1])


  - Gaussian Noise with 0.5 stdev:
	Test loss:	 1.4783432458877563
	Test accuracy:	 0.6273

  - Gaussian Noise with 0.1 stdev:
	Test loss:	 0.8635457564353943
	Test accuracy:	 0.7043

  - Gaussian Noise with 0.05 stdev:
	Test loss:	 0.8434040348052978
	Test accuracy:	 0.7109

  - Gaussian Noise with 0.02 stdev:
	Test loss:	 0.809952991771698
	Test accuracy:	 0.727

  - Gaussian Noise with 0.01 stdev:
	Test loss:	 0.7354572436332703
	Test accuracy:	 0.7488


Best results:
  - Gaussian Noise with 0.02 stdev:
	Test loss:	 0.809952991771698
	Test accuracy:	 0.727


### 2) Add layers to the network to see if can improve performance

#### First model: batch normalization

In [18]:
from keras.layers.normalization import BatchNormalization

model = Sequential()

model.add(Conv2D(32, (3, 3), padding='same',
                 input_shape=x_train.shape[1:]))

model.add(BatchNormalization())

model.add(Activation('relu'))
model.add(Conv2D(32, (3, 3)))

model.add(BatchNormalization())

model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(64, (3, 3), padding='same'))

model.add(BatchNormalization())

model.add(Activation('relu'))
model.add(Conv2D(64, (3, 3)))

model.add(BatchNormalization())

model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer=opt,
                metrics=['accuracy'])
model.fit(x_train, y_train,
            batch_size=batch_size,
            epochs=epochs,
            validation_data=(x_test, y_test),
            shuffle=True)

model.save('cifra10_batch.h5')


Train on 50000 samples, validate on 10000 samples
Epoch 1/20
50000/50000 [==============================] - 21s 429us/step - loss: 1.9740 - acc: 0.2997 - val_loss: 1.5177 - val_acc: 0.4549
Epoch 2/20
50000/50000 [==============================] - 19s 370us/step - loss: 1.5783 - acc: 0.4229 - val_loss: 1.4144 - val_acc: 0.4909
Epoch 3/20
 3072/50000 [>.............................] - ETA: 16s - loss: 1.4976 - acc: 0.4502

50000/50000 [==============================] - 19s 377us/step - loss: 1.4466 - acc: 0.4774 - val_loss: 1.2602 - val_acc: 0.5471
Epoch 4/20
50000/50000 [==============================] - 18s 365us/step - loss: 1.3561 - acc: 0.5111 - val_loss: 1.2602 - val_acc: 0.5517
Epoch 5/20
25600/50000 [==============>...............] - ETA: 8s - loss: 1.2975 - acc: 0.5344

50000/50000 [==============================] - 18s 369us/step - loss: 1.2847 - acc: 0.5400 - val_loss: 1.1074 - val_acc: 0.6093
Epoch 6/20
50000/50000 [==============================] - 18s 368us/step - loss: 1.2142 - acc: 0.5655 - val_loss: 1.1484 - val_acc: 0.5939
Epoch 7/20
31104/50000 [=================>............] - ETA: 6s - loss: 1.1615 - acc: 0.5832

50000/50000 [==============================] - 18s 365us/step - loss: 1.1526 - acc: 0.5880 - val_loss: 1.0022 - val_acc: 0.6477
Epoch 8/20
50000/50000 [==============================] - 18s 367us/step - loss: 1.1000 - acc: 0.6082 - val_loss: 0.9663 - val_acc: 0.6614
Epoch 9/20
32768/50000 [==================>...........] - ETA: 5s - loss: 1.0502 - acc: 0.6259

50000/50000 [==============================] - 18s 366us/step - loss: 1.0478 - acc: 0.6268 - val_loss: 0.9367 - val_acc: 0.6709
Epoch 10/20
50000/50000 [==============================] - 18s 364us/step - loss: 1.0060 - acc: 0.6409 - val_loss: 0.9728 - val_acc: 0.6590
Epoch 11/20
32640/50000 [==================>...........] - ETA: 5s - loss: 0.9759 - acc: 0.6542

50000/50000 [==============================] - 18s 367us/step - loss: 0.9728 - acc: 0.6564 - val_loss: 0.8689 - val_acc: 0.6989
Epoch 12/20
50000/50000 [==============================] - 19s 372us/step - loss: 0.9328 - acc: 0.6684 - val_loss: 0.8626 - val_acc: 0.6951
Epoch 13/20
30336/50000 [=================>............] - ETA: 6s - loss: 0.9149 - acc: 0.6770

50000/50000 [==============================] - 18s 368us/step - loss: 0.9107 - acc: 0.6791 - val_loss: 0.8522 - val_acc: 0.7028
Epoch 14/20
50000/50000 [==============================] - 18s 366us/step - loss: 0.8729 - acc: 0.6928 - val_loss: 0.8268 - val_acc: 0.7134
Epoch 15/20
31488/50000 [=================>............] - ETA: 6s - loss: 0.8543 - acc: 0.6981

50000/50000 [==============================] - 18s 366us/step - loss: 0.8518 - acc: 0.7000 - val_loss: 0.8909 - val_acc: 0.6888
Epoch 16/20
50000/50000 [==============================] - 18s 365us/step - loss: 0.8348 - acc: 0.7042 - val_loss: 0.8392 - val_acc: 0.7082
Epoch 17/20
31616/50000 [=================>............] - ETA: 6s - loss: 0.8192 - acc: 0.7125

50000/50000 [==============================] - 18s 366us/step - loss: 0.8116 - acc: 0.7155 - val_loss: 0.7811 - val_acc: 0.7275
Epoch 18/20
50000/50000 [==============================] - 18s 367us/step - loss: 0.7879 - acc: 0.7214 - val_loss: 0.9236 - val_acc: 0.6898
Epoch 19/20
31104/50000 [=================>............] - ETA: 6s - loss: 0.7789 - acc: 0.7260

50000/50000 [==============================] - 19s 370us/step - loss: 0.7756 - acc: 0.7258 - val_loss: 0.8088 - val_acc: 0.7243
Epoch 20/20
50000/50000 [==============================] - 18s 369us/step - loss: 0.7515 - acc: 0.7370 - val_loss: 0.7678 - val_acc: 0.7365


In [19]:

model = keras.models.load_model('cifra10_batch.h5')
print('\n  - Model with Batch Normalization:')
scores = model.evaluate(x_test, y_test, verbose=0)
print('\tTest loss:\t', scores[0])
print('\tTest accuracy:\t', scores[1])

Y_pred = model.predict(x_test, verbose=2)
cm = confusion_matrix(np.argmax(y_test,axis=1),np.argmax(Y_pred, axis=1))
print('\tConfusion Matrix:\t')
print(cm)


  - Model with Batch Normalization:
	Test loss:	 0.7677783198356628
	Test accuracy:	 0.7365
	Confusion Matrix:	
[[652  14  56  37  38   9  12  19  96  67]
 [  4 774   4  12   9   9  20   6  32 130]
 [ 44   2 496 103 138  89  81  24  11  12]
 [  8   2  23 615  69 176  71  20   7   9]
 [  6   0  17  72 779  33  50  33   8   2]
 [  5   1   9 198  59 679  14  33   1   1]
 [  2   0  16  61  29  27 860   3   2   0]
 [  3   0   8  44  81  74   6 774   3   7]
 [ 20  18   7  25  11   9   6   2 878  24]
 [ 13  38   4  13  14  10   7  13  30 858]]


#### Second model: regularizer

In [20]:
from keras.layers.normalization import BatchNormalization
from keras import regularizers

weight_decay = 1e-4

model = Sequential()

model.add(Conv2D(32, (3, 3), padding='same',
                 input_shape=x_train.shape[1:]))

model.add(Activation('relu'))
model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(64, (3, 3), padding='same', kernel_regularizer=regularizers.l2(weight_decay)))
model.add(Activation('relu'))
model.add(Conv2D(64, (3, 3), kernel_regularizer=regularizers.l2(weight_decay)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer=opt,
                metrics=['accuracy'])
model.fit(x_train, y_train,
            batch_size=batch_size,
            epochs=epochs,
            validation_data=(x_test, y_test),
            shuffle=True)

model.save('cifra10_regL2.h5')

Train on 50000 samples, validate on 10000 samples
Epoch 1/20
50000/50000 [==============================] - 16s 322us/step - loss: 1.9914 - acc: 0.2747 - val_loss: 1.7675 - val_acc: 0.3713
Epoch 2/20
50000/50000 [==============================] - 14s 281us/step - loss: 1.6977 - acc: 0.3872 - val_loss: 1.5543 - val_acc: 0.4453
Epoch 3/20
 5248/50000 [==>...........................] - ETA: 11s - loss: 1.6367 - acc: 0.4059

50000/50000 [==============================] - 14s 277us/step - loss: 1.5844 - acc: 0.4289 - val_loss: 1.4826 - val_acc: 0.4710
Epoch 4/20
50000/50000 [==============================] - 14s 279us/step - loss: 1.5024 - acc: 0.4603 - val_loss: 1.3937 - val_acc: 0.5070
Epoch 5/20
25728/50000 [==============>...............] - ETA: 6s - loss: 1.4529 - acc: 0.4773

50000/50000 [==============================] - 14s 280us/step - loss: 1.4393 - acc: 0.4835 - val_loss: 1.3528 - val_acc: 0.5171
Epoch 6/20
50000/50000 [==============================] - 14s 273us/step - loss: 1.3878 - acc: 0.5038 - val_loss: 1.3348 - val_acc: 0.5230
Epoch 7/20
28800/50000 [================>.............] - ETA: 5s - loss: 1.3558 - acc: 0.5169

50000/50000 [==============================] - 14s 276us/step - loss: 1.3420 - acc: 0.5215 - val_loss: 1.2523 - val_acc: 0.5599
Epoch 8/20
50000/50000 [==============================] - 14s 278us/step - loss: 1.3025 - acc: 0.5393 - val_loss: 1.2629 - val_acc: 0.5478
Epoch 9/20
28544/50000 [================>.............] - ETA: 5s - loss: 1.2677 - acc: 0.5520

50000/50000 [==============================] - 14s 275us/step - loss: 1.2664 - acc: 0.5525 - val_loss: 1.2043 - val_acc: 0.5753
Epoch 10/20
50000/50000 [==============================] - 14s 276us/step - loss: 1.2343 - acc: 0.5663 - val_loss: 1.1654 - val_acc: 0.5924
Epoch 11/20
29312/50000 [================>.............] - ETA: 5s - loss: 1.1994 - acc: 0.5787

50000/50000 [==============================] - 14s 281us/step - loss: 1.2010 - acc: 0.5776 - val_loss: 1.1767 - val_acc: 0.5929
Epoch 12/20
50000/50000 [==============================] - 14s 286us/step - loss: 1.1708 - acc: 0.5897 - val_loss: 1.1215 - val_acc: 0.6095
Epoch 13/20
30208/50000 [=================>............] - ETA: 5s - loss: 1.1416 - acc: 0.6026

50000/50000 [==============================] - 14s 287us/step - loss: 1.1432 - acc: 0.6019 - val_loss: 1.0666 - val_acc: 0.6273
Epoch 14/20
50000/50000 [==============================] - 14s 283us/step - loss: 1.1170 - acc: 0.6106 - val_loss: 1.0436 - val_acc: 0.6411
Epoch 15/20
31104/50000 [=================>............] - ETA: 5s - loss: 1.0912 - acc: 0.6192

50000/50000 [==============================] - 14s 281us/step - loss: 1.0899 - acc: 0.6214 - val_loss: 1.0521 - val_acc: 0.6398
Epoch 16/20
50000/50000 [==============================] - 14s 284us/step - loss: 1.0726 - acc: 0.6278 - val_loss: 1.0147 - val_acc: 0.6502
Epoch 17/20
30464/50000 [=================>............] - ETA: 5s - loss: 1.0606 - acc: 0.6332

50000/50000 [==============================] - 14s 283us/step - loss: 1.0515 - acc: 0.6354 - val_loss: 0.9949 - val_acc: 0.6575
Epoch 18/20
50000/50000 [==============================] - 14s 283us/step - loss: 1.0303 - acc: 0.6419 - val_loss: 0.9667 - val_acc: 0.6704
Epoch 19/20
32896/50000 [==================>...........] - ETA: 4s - loss: 1.0048 - acc: 0.6498

50000/50000 [==============================] - 14s 282us/step - loss: 1.0096 - acc: 0.6483 - val_loss: 0.9837 - val_acc: 0.6621
Epoch 20/20
50000/50000 [==============================] - 14s 282us/step - loss: 0.9918 - acc: 0.6543 - val_loss: 0.9333 - val_acc: 0.6795


In [21]:
model= keras.models.load_model('cifra10_regL2.h5')
print('\n  - regularizer L2:')
scores = model.evaluate(x_test, y_test, verbose=0)
print('\tTest loss:\t', scores[0])
print('\tTest accuracy:\t', scores[1])

Y_pred = model.predict(x_test, verbose=2)
cm = confusion_matrix(np.argmax(y_test,axis=1),np.argmax(Y_pred, axis=1))
print('\tConfusion Matrix:\t')
print(cm)


  - regularizer L2:
	Test loss:	 0.9333020919799805
	Test accuracy:	 0.6795
	Confusion Matrix:	
[[700  36  52  21   9  14  20  10  95  43]
 [ 21 826   3   9   2   4  14   3  29  89]
 [ 76  10 503  56 105  86  92  35  20  17]
 [ 15  11  77 427  61 209 114  40  19  27]
 [ 27   4  74  43 561  57 110 106  15   3]
 [ 11   5  56 124  40 655  46  45   7  11]
 [  9   6  39  36  31  24 827  11   5  12]
 [ 19   4  31  38  53  86  14 723   6  26]
 [ 61  45  15   7   4   6   9   2 814  37]
 [ 33 109   9  12   8   4  16  19  31 759]]


### 3) Try another method for dealing with overfitting

In [22]:
from keras.layers.normalization import BatchNormalization
from keras import regularizers

weight_decay = 1e-4

model = Sequential()

model.add(Conv2D(32, (3, 3), padding='same',
                 input_shape=x_train.shape[1:]))

model.add(BatchNormalization())

model.add(Activation('relu'))
model.add(Conv2D(32, (3, 3)))

model.add(BatchNormalization())

model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(64, (3, 3), padding='same', kernel_regularizer=regularizers.l2(weight_decay)))

model.add(BatchNormalization())

model.add(Activation('relu'))
model.add(Conv2D(64, (3, 3), kernel_regularizer=regularizers.l2(weight_decay)))

model.add(BatchNormalization())

model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer=opt,
                metrics=['accuracy'])
model.fit(x_train, y_train,
            batch_size=batch_size,
            epochs=epochs,
            validation_data=(x_test, y_test),
            shuffle=True)

model.save('cifra10_batch_regL2.h5')

Train on 50000 samples, validate on 10000 samples
Epoch 1/20
50000/50000 [==============================] - 23s 460us/step - loss: 1.9712 - acc: 0.3017 - val_loss: 1.5671 - val_acc: 0.4336
Epoch 2/20
49536/50000 [============================>.] - ETA: 0s - loss: 1.5809 - acc: 0.4282

50000/50000 [==============================] - 19s 378us/step - loss: 1.5796 - acc: 0.4287 - val_loss: 1.3653 - val_acc: 0.5095
Epoch 3/20
50000/50000 [==============================] - 19s 375us/step - loss: 1.4432 - acc: 0.4850 - val_loss: 1.3360 - val_acc: 0.5239
Epoch 4/20
36096/50000 [====================>.........] - ETA: 4s - loss: 1.3671 - acc: 0.5135

50000/50000 [==============================] - 18s 366us/step - loss: 1.3585 - acc: 0.5157 - val_loss: 1.2537 - val_acc: 0.5539
Epoch 5/20
50000/50000 [==============================] - 18s 364us/step - loss: 1.2891 - acc: 0.5448 - val_loss: 1.1363 - val_acc: 0.6038
Epoch 6/20
34944/50000 [===================>..........] - ETA: 5s - loss: 1.2304 - acc: 0.5660

50000/50000 [==============================] - 18s 361us/step - loss: 1.2193 - acc: 0.5698 - val_loss: 1.1096 - val_acc: 0.6114
Epoch 7/20
50000/50000 [==============================] - 18s 363us/step - loss: 1.1713 - acc: 0.5870 - val_loss: 1.0484 - val_acc: 0.6338
Epoch 8/20
34304/50000 [===================>..........] - ETA: 5s - loss: 1.1230 - acc: 0.6037

50000/50000 [==============================] - 18s 363us/step - loss: 1.1163 - acc: 0.6051 - val_loss: 1.0196 - val_acc: 0.6398
Epoch 9/20
50000/50000 [==============================] - 18s 362us/step - loss: 1.0674 - acc: 0.6253 - val_loss: 0.9619 - val_acc: 0.6624
Epoch 10/20
33664/50000 [===================>..........] - ETA: 5s - loss: 1.0315 - acc: 0.6371

50000/50000 [==============================] - 18s 364us/step - loss: 1.0279 - acc: 0.6390 - val_loss: 0.9230 - val_acc: 0.6802
Epoch 11/20
50000/50000 [==============================] - 18s 364us/step - loss: 0.9964 - acc: 0.6519 - val_loss: 0.9402 - val_acc: 0.6727
Epoch 12/20
34048/50000 [===================>..........] - ETA: 5s - loss: 0.9647 - acc: 0.6623

50000/50000 [==============================] - 18s 367us/step - loss: 0.9610 - acc: 0.6648 - val_loss: 0.8788 - val_acc: 0.6943
Epoch 13/20
50000/50000 [==============================] - 18s 365us/step - loss: 0.9343 - acc: 0.6735 - val_loss: 0.8759 - val_acc: 0.6955
Epoch 14/20
33152/50000 [==================>...........] - ETA: 5s - loss: 0.9081 - acc: 0.6822

50000/50000 [==============================] - 18s 370us/step - loss: 0.9101 - acc: 0.6819 - val_loss: 0.8369 - val_acc: 0.7076
Epoch 15/20
50000/50000 [==============================] - 18s 369us/step - loss: 0.8866 - acc: 0.6897 - val_loss: 0.8433 - val_acc: 0.7059
Epoch 16/20
32000/50000 [==================>...........] - ETA: 6s - loss: 0.8689 - acc: 0.6983

50000/50000 [==============================] - 18s 370us/step - loss: 0.8667 - acc: 0.6991 - val_loss: 0.7807 - val_acc: 0.7315
Epoch 17/20
50000/50000 [==============================] - 18s 369us/step - loss: 0.8454 - acc: 0.7041 - val_loss: 0.7916 - val_acc: 0.7242
Epoch 18/20
32384/50000 [==================>...........] - ETA: 6s - loss: 0.8211 - acc: 0.7132

50000/50000 [==============================] - 18s 367us/step - loss: 0.8249 - acc: 0.7120 - val_loss: 0.7565 - val_acc: 0.7384
Epoch 19/20
50000/50000 [==============================] - 18s 366us/step - loss: 0.8069 - acc: 0.7196 - val_loss: 0.8221 - val_acc: 0.7177
Epoch 20/20
33664/50000 [===================>..........] - ETA: 5s - loss: 0.7873 - acc: 0.7258

50000/50000 [==============================] - 18s 369us/step - loss: 0.7902 - acc: 0.7248 - val_loss: 0.7412 - val_acc: 0.7442


In [23]:
model.save('cifra10_batch_regL2.h5')
print('\n  - Model with batch normalization and regularizer:')
scores = model.evaluate(x_test, y_test, verbose=0)
print('\tTest loss:\t', scores[0])
print('\tTest accuracy:\t', scores[1])


  - Model with batch normalization and regularizer:
	Test loss:	 0.741171202468872
	Test accuracy:	 0.7442


In [24]:
model = keras.models.load_model('cifra10_batch.h5')
model.add(keras.layers.GaussianNoise(0.01))
model.compile(loss='categorical_crossentropy',
              optimizer=opt,
                metrics=['accuracy'])
model.fit(x_train, y_train,
            batch_size=batch_size,
            epochs=epochs,
            validation_data=(x_test, y_test),
            shuffle=True)
model.save('cifra10_batch_n0.01.h5')

Train on 50000 samples, validate on 10000 samples
Epoch 1/20
50000/50000 [==============================] - 22s 450us/step - loss: 0.7906 - acc: 0.7374 - val_loss: 0.7849 - val_acc: 0.7295
Epoch 2/20
50000/50000 [==============================] - 18s 366us/step - loss: 0.7871 - acc: 0.7414 - val_loss: 0.7306 - val_acc: 0.7518
Epoch 3/20
 1408/50000 [..............................] - ETA: 16s - loss: 0.7760 - acc: 0.7393

50000/50000 [==============================] - 18s 370us/step - loss: 0.7684 - acc: 0.7458 - val_loss: 0.7336 - val_acc: 0.7472
Epoch 4/20
50000/50000 [==============================] - 18s 368us/step - loss: 0.7650 - acc: 0.7470 - val_loss: 0.7358 - val_acc: 0.7494
Epoch 5/20
24960/50000 [=============>................] - ETA: 8s - loss: 0.7389 - acc: 0.7535

50000/50000 [==============================] - 18s 365us/step - loss: 0.7528 - acc: 0.7521 - val_loss: 0.7010 - val_acc: 0.7613
Epoch 6/20
50000/50000 [==============================] - 18s 368us/step - loss: 0.7430 - acc: 0.7567 - val_loss: 0.8109 - val_acc: 0.7279
Epoch 7/20
30464/50000 [=================>............] - ETA: 6s - loss: 0.7277 - acc: 0.7580

50000/50000 [==============================] - 18s 369us/step - loss: 0.7253 - acc: 0.7587 - val_loss: 0.6730 - val_acc: 0.7674
Epoch 8/20
50000/50000 [==============================] - 19s 372us/step - loss: 0.7248 - acc: 0.7660 - val_loss: 0.6886 - val_acc: 0.7610
Epoch 9/20
30208/50000 [=================>............] - ETA: 6s - loss: 0.6948 - acc: 0.7682

50000/50000 [==============================] - 19s 374us/step - loss: 0.7075 - acc: 0.7658 - val_loss: 0.7130 - val_acc: 0.7557
Epoch 10/20
50000/50000 [==============================] - 19s 370us/step - loss: 0.6985 - acc: 0.7703 - val_loss: 0.7365 - val_acc: 0.7492
Epoch 11/20
28672/50000 [================>.............] - ETA: 7s - loss: 0.6882 - acc: 0.7743

50000/50000 [==============================] - 20s 394us/step - loss: 0.6938 - acc: 0.7731 - val_loss: 0.6836 - val_acc: 0.7663
Epoch 12/20
50000/50000 [==============================] - 18s 369us/step - loss: 0.6840 - acc: 0.7771 - val_loss: 0.6573 - val_acc: 0.7736
Epoch 13/20
30080/50000 [=================>............] - ETA: 6s - loss: 0.6703 - acc: 0.7775

50000/50000 [==============================] - 19s 370us/step - loss: 0.6703 - acc: 0.7776 - val_loss: 0.6487 - val_acc: 0.7783
Epoch 14/20
50000/50000 [==============================] - 19s 372us/step - loss: 0.6606 - acc: 0.7848 - val_loss: 0.6580 - val_acc: 0.7764
Epoch 15/20
29824/50000 [================>.............] - ETA: 7s - loss: 0.6634 - acc: 0.7836

50000/50000 [==============================] - 19s 371us/step - loss: 0.6654 - acc: 0.7829 - val_loss: 0.6608 - val_acc: 0.7703
Epoch 16/20
50000/50000 [==============================] - 19s 371us/step - loss: 0.6557 - acc: 0.7863 - val_loss: 0.6736 - val_acc: 0.7708
Epoch 17/20
30080/50000 [=================>............] - ETA: 6s - loss: 0.6368 - acc: 0.7903

50000/50000 [==============================] - 19s 370us/step - loss: 0.6393 - acc: 0.7889 - val_loss: 0.6606 - val_acc: 0.7732
Epoch 18/20
50000/50000 [==============================] - 19s 372us/step - loss: 0.6301 - acc: 0.7923 - val_loss: 0.6260 - val_acc: 0.7845
Epoch 19/20
29440/50000 [================>.............] - ETA: 7s - loss: 0.6302 - acc: 0.7950

50000/50000 [==============================] - 19s 372us/step - loss: 0.6328 - acc: 0.7941 - val_loss: 0.6621 - val_acc: 0.7774
Epoch 20/20
50000/50000 [==============================] - 19s 371us/step - loss: 0.6183 - acc: 0.7972 - val_loss: 0.6950 - val_acc: 0.7682


In [25]:
model = keras.models.load_model('cifra10_batch_n0.01.h5')

print('\n  - Model with Batch Normalization and Gaussian Noise with 0.01 stdev:')
scores = model.evaluate(x_test, y_test, verbose=0)
print('\tTest loss:\t', scores[0])
print('\tTest accuracy:\t', scores[1])


  - Model with Batch Normalization and Gaussian Noise with 0.01 stdev:
	Test loss:	 0.6949894082069397
	Test accuracy:	 0.7682
